//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenerresultados_webxsystemuserResult"/> and <see cref="obtenerresultados_webxsystemuserResultDto"/>.
    /// </summary>
    public static partial class obtenerresultados_webxsystemuserResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenerresultados_webxsystemuserResultDto"/> converted from <see cref="obtenerresultados_webxsystemuserResult"/>.</param>
        static partial void OnDTO(this obtenerresultados_webxsystemuserResult entity, obtenerresultados_webxsystemuserResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenerresultados_webxsystemuserResult"/> converted from <see cref="obtenerresultados_webxsystemuserResultDto"/>.</param>
        static partial void OnEntity(this obtenerresultados_webxsystemuserResultDto dto, obtenerresultados_webxsystemuserResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenerresultados_webxsystemuserResultDto"/> to an instance of <see cref="obtenerresultados_webxsystemuserResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenerresultados_webxsystemuserResultDto"/> to convert.</param>
        public static obtenerresultados_webxsystemuserResult ToEntity(this obtenerresultados_webxsystemuserResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenerresultados_webxsystemuserResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;
            entity.Paciente = dto.Paciente;
            entity.Fecha = dto.Fecha;
            entity.v_Name = dto.v_Name;
            entity.v_ProtocolId = dto.v_ProtocolId;
            entity.Protocolo = dto.Protocolo;
            entity.ESTADO = dto.ESTADO;
            entity.PENDIENTE = dto.PENDIENTE;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenerresultados_webxsystemuserResult"/> to an instance of <see cref="obtenerresultados_webxsystemuserResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenerresultados_webxsystemuserResult"/> to convert.</param>
        public static obtenerresultados_webxsystemuserResultDto ToDTO(this obtenerresultados_webxsystemuserResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenerresultados_webxsystemuserResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;
            dto.Paciente = entity.Paciente;
            dto.Fecha = entity.Fecha;
            dto.v_Name = entity.v_Name;
            dto.v_ProtocolId = entity.v_ProtocolId;
            dto.Protocolo = entity.Protocolo;
            dto.ESTADO = entity.ESTADO;
            dto.PENDIENTE = entity.PENDIENTE;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerresultados_webxsystemuserResultDto"/> to an instance of <see cref="obtenerresultados_webxsystemuserResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenerresultados_webxsystemuserResult> ToEntities(this IEnumerable<obtenerresultados_webxsystemuserResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerresultados_webxsystemuserResult"/> to an instance of <see cref="obtenerresultados_webxsystemuserResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenerresultados_webxsystemuserResultDto> ToDTOs(this IEnumerable<obtenerresultados_webxsystemuserResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
