//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenerserviciosxpacienteResult"/> and <see cref="obtenerserviciosxpacienteResultDto"/>.
    /// </summary>
    public static partial class obtenerserviciosxpacienteResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenerserviciosxpacienteResultDto"/> converted from <see cref="obtenerserviciosxpacienteResult"/>.</param>
        static partial void OnDTO(this obtenerserviciosxpacienteResult entity, obtenerserviciosxpacienteResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenerserviciosxpacienteResult"/> converted from <see cref="obtenerserviciosxpacienteResultDto"/>.</param>
        static partial void OnEntity(this obtenerserviciosxpacienteResultDto dto, obtenerserviciosxpacienteResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenerserviciosxpacienteResultDto"/> to an instance of <see cref="obtenerserviciosxpacienteResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenerserviciosxpacienteResultDto"/> to convert.</param>
        public static obtenerserviciosxpacienteResult ToEntity(this obtenerserviciosxpacienteResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenerserviciosxpacienteResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.PACIENTE = dto.PACIENTE;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.EDAD = dto.EDAD;
            entity.RUCCLI = dto.RUCCLI;
            entity.CLIENTE = dto.CLIENTE;
            entity.RUCFACT = dto.RUCFACT;
            entity.EMPFACT = dto.EMPFACT;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.PRECTOTAL = dto.PRECTOTAL;
            entity.v_UserName = dto.v_UserName;
            entity.Estado = dto.Estado;
            entity.cdoc_Serie = dto.cdoc_Serie;
            entity.cdoc_nro = dto.cdoc_nro;
            entity.cusu_crea = dto.cusu_crea;
            entity.v_comment = dto.v_comment;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenerserviciosxpacienteResult"/> to an instance of <see cref="obtenerserviciosxpacienteResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenerserviciosxpacienteResult"/> to convert.</param>
        public static obtenerserviciosxpacienteResultDto ToDTO(this obtenerserviciosxpacienteResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenerserviciosxpacienteResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.PACIENTE = entity.PACIENTE;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.EDAD = entity.EDAD;
            dto.RUCCLI = entity.RUCCLI;
            dto.CLIENTE = entity.CLIENTE;
            dto.RUCFACT = entity.RUCFACT;
            dto.EMPFACT = entity.EMPFACT;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.PRECTOTAL = entity.PRECTOTAL;
            dto.v_UserName = entity.v_UserName;
            dto.Estado = entity.Estado;
            dto.cdoc_Serie = entity.cdoc_Serie;
            dto.cdoc_nro = entity.cdoc_nro;
            dto.cusu_crea = entity.cusu_crea;
            dto.v_comment = entity.v_comment;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerserviciosxpacienteResultDto"/> to an instance of <see cref="obtenerserviciosxpacienteResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenerserviciosxpacienteResult> ToEntities(this IEnumerable<obtenerserviciosxpacienteResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerserviciosxpacienteResult"/> to an instance of <see cref="obtenerserviciosxpacienteResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenerserviciosxpacienteResultDto> ToDTOs(this IEnumerable<obtenerserviciosxpacienteResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
