//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:02
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenerserviciosResult"/> and <see cref="obtenerserviciosResultDto"/>.
    /// </summary>
    public static partial class obtenerserviciosResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenerserviciosResultDto"/> converted from <see cref="obtenerserviciosResult"/>.</param>
        static partial void OnDTO(this obtenerserviciosResult entity, obtenerserviciosResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenerserviciosResult"/> converted from <see cref="obtenerserviciosResultDto"/>.</param>
        static partial void OnEntity(this obtenerserviciosResultDto dto, obtenerserviciosResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenerserviciosResultDto"/> to an instance of <see cref="obtenerserviciosResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenerserviciosResultDto"/> to convert.</param>
        public static obtenerserviciosResult ToEntity(this obtenerserviciosResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenerserviciosResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.Trabajador = dto.Trabajador;
            entity.i_SexTypeId = dto.i_SexTypeId;
            entity.v_Name = dto.v_Name;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenerserviciosResult"/> to an instance of <see cref="obtenerserviciosResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenerserviciosResult"/> to convert.</param>
        public static obtenerserviciosResultDto ToDTO(this obtenerserviciosResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenerserviciosResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.Trabajador = entity.Trabajador;
            dto.i_SexTypeId = entity.i_SexTypeId;
            dto.v_Name = entity.v_Name;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerserviciosResultDto"/> to an instance of <see cref="obtenerserviciosResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenerserviciosResult> ToEntities(this IEnumerable<obtenerserviciosResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerserviciosResult"/> to an instance of <see cref="obtenerserviciosResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenerserviciosResultDto> ToDTOs(this IEnumerable<obtenerserviciosResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
