//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="validacionreportes"/> and <see cref="validacionreportesDto"/>.
    /// </summary>
    public static partial class validacionreportesAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="validacionreportesDto"/> converted from <see cref="validacionreportes"/>.</param>
        static partial void OnDTO(this validacionreportes entity, validacionreportesDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="validacionreportes"/> converted from <see cref="validacionreportesDto"/>.</param>
        static partial void OnEntity(this validacionreportesDto dto, validacionreportes entity);

        /// <summary>
        /// Converts this instance of <see cref="validacionreportesDto"/> to an instance of <see cref="validacionreportes"/>.
        /// </summary>
        /// <param name="dto"><see cref="validacionreportesDto"/> to convert.</param>
        public static validacionreportes ToEntity(this validacionreportesDto dto)
        {
            if (dto == null) return null;

            var entity = new validacionreportes();

            entity.i_ValidacionReporteId = dto.i_ValidacionReporteId;
            entity.ReporteId = dto.ReporteId;
            entity.i_IsDeleted = dto.i_IsDeleted;
            entity.i_InsertUserId = dto.i_InsertUserId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.i_UpdateUserId = dto.i_UpdateUserId;
            entity.d_UpdateDate = dto.d_UpdateDate;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="validacionreportes"/> to an instance of <see cref="validacionreportesDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="validacionreportes"/> to convert.</param>
        public static validacionreportesDto ToDTO(this validacionreportes entity)
        {
            if (entity == null) return null;

            var dto = new validacionreportesDto();

            dto.i_ValidacionReporteId = entity.i_ValidacionReporteId;
            dto.ReporteId = entity.ReporteId;
            dto.i_IsDeleted = entity.i_IsDeleted;
            dto.i_InsertUserId = entity.i_InsertUserId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.i_UpdateUserId = entity.i_UpdateUserId;
            dto.d_UpdateDate = entity.d_UpdateDate;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="validacionreportesDto"/> to an instance of <see cref="validacionreportes"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<validacionreportes> ToEntities(this IEnumerable<validacionreportesDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="validacionreportes"/> to an instance of <see cref="validacionreportesDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<validacionreportesDto> ToDTOs(this IEnumerable<validacionreportes> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
