//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="vieresultadoswebbackup"/> and <see cref="vieresultadoswebbackupDto"/>.
    /// </summary>
    public static partial class vieresultadoswebbackupAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="vieresultadoswebbackupDto"/> converted from <see cref="vieresultadoswebbackup"/>.</param>
        static partial void OnDTO(this vieresultadoswebbackup entity, vieresultadoswebbackupDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="vieresultadoswebbackup"/> converted from <see cref="vieresultadoswebbackupDto"/>.</param>
        static partial void OnEntity(this vieresultadoswebbackupDto dto, vieresultadoswebbackup entity);

        /// <summary>
        /// Converts this instance of <see cref="vieresultadoswebbackupDto"/> to an instance of <see cref="vieresultadoswebbackup"/>.
        /// </summary>
        /// <param name="dto"><see cref="vieresultadoswebbackupDto"/> to convert.</param>
        public static vieresultadoswebbackup ToEntity(this vieresultadoswebbackupDto dto)
        {
            if (dto == null) return null;

            var entity = new vieresultadoswebbackup();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;
            entity.PACIENTE = dto.PACIENTE;
            entity.FECHA = dto.FECHA;
            entity.v_Name = dto.v_Name;
            entity.v_ProtocolId = dto.v_ProtocolId;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.v_Value100 = dto.v_Value100;
            entity.v_Value200 = dto.v_Value200;
            entity.i_SystemUserId = dto.i_SystemUserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="vieresultadoswebbackup"/> to an instance of <see cref="vieresultadoswebbackupDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="vieresultadoswebbackup"/> to convert.</param>
        public static vieresultadoswebbackupDto ToDTO(this vieresultadoswebbackup entity)
        {
            if (entity == null) return null;

            var dto = new vieresultadoswebbackupDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;
            dto.PACIENTE = entity.PACIENTE;
            dto.FECHA = entity.FECHA;
            dto.v_Name = entity.v_Name;
            dto.v_ProtocolId = entity.v_ProtocolId;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.v_Value100 = entity.v_Value100;
            dto.v_Value200 = entity.v_Value200;
            dto.i_SystemUserId = entity.i_SystemUserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="vieresultadoswebbackupDto"/> to an instance of <see cref="vieresultadoswebbackup"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<vieresultadoswebbackup> ToEntities(this IEnumerable<vieresultadoswebbackupDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="vieresultadoswebbackup"/> to an instance of <see cref="vieresultadoswebbackupDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<vieresultadoswebbackupDto> ToDTOs(this IEnumerable<vieresultadoswebbackup> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
