//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="viewgetcalendarxcategory"/> and <see cref="viewgetcalendarxcategoryDto"/>.
    /// </summary>
    public static partial class viewgetcalendarxcategoryAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="viewgetcalendarxcategoryDto"/> converted from <see cref="viewgetcalendarxcategory"/>.</param>
        static partial void OnDTO(this viewgetcalendarxcategory entity, viewgetcalendarxcategoryDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="viewgetcalendarxcategory"/> converted from <see cref="viewgetcalendarxcategoryDto"/>.</param>
        static partial void OnEntity(this viewgetcalendarxcategoryDto dto, viewgetcalendarxcategory entity);

        /// <summary>
        /// Converts this instance of <see cref="viewgetcalendarxcategoryDto"/> to an instance of <see cref="viewgetcalendarxcategory"/>.
        /// </summary>
        /// <param name="dto"><see cref="viewgetcalendarxcategoryDto"/> to convert.</param>
        public static viewgetcalendarxcategory ToEntity(this viewgetcalendarxcategoryDto dto)
        {
            if (dto == null) return null;

            var entity = new viewgetcalendarxcategory();

            entity.d_CircuitStartDate = dto.d_CircuitStartDate;
            entity.Paciente = dto.Paciente;
            entity.NroDocum = dto.NroDocum;
            entity.Edad = dto.Edad;
            entity.Empleador = dto.Empleador;
            entity.Cliente = dto.Cliente;
            entity.Protocolo = dto.Protocolo;
            entity.v_Value1 = dto.v_Value1;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.i_IsVipId = dto.i_IsVipId;
            entity.i_CategoryId = dto.i_CategoryId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="viewgetcalendarxcategory"/> to an instance of <see cref="viewgetcalendarxcategoryDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="viewgetcalendarxcategory"/> to convert.</param>
        public static viewgetcalendarxcategoryDto ToDTO(this viewgetcalendarxcategory entity)
        {
            if (entity == null) return null;

            var dto = new viewgetcalendarxcategoryDto();

            dto.d_CircuitStartDate = entity.d_CircuitStartDate;
            dto.Paciente = entity.Paciente;
            dto.NroDocum = entity.NroDocum;
            dto.Edad = entity.Edad;
            dto.Empleador = entity.Empleador;
            dto.Cliente = entity.Cliente;
            dto.Protocolo = entity.Protocolo;
            dto.v_Value1 = entity.v_Value1;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.i_IsVipId = entity.i_IsVipId;
            dto.i_CategoryId = entity.i_CategoryId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="viewgetcalendarxcategoryDto"/> to an instance of <see cref="viewgetcalendarxcategory"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<viewgetcalendarxcategory> ToEntities(this IEnumerable<viewgetcalendarxcategoryDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="viewgetcalendarxcategory"/> to an instance of <see cref="viewgetcalendarxcategoryDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<viewgetcalendarxcategoryDto> ToDTOs(this IEnumerable<viewgetcalendarxcategory> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
