//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="viewgetservicexpac"/> and <see cref="viewgetservicexpacDto"/>.
    /// </summary>
    public static partial class viewgetservicexpacAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="viewgetservicexpacDto"/> converted from <see cref="viewgetservicexpac"/>.</param>
        static partial void OnDTO(this viewgetservicexpac entity, viewgetservicexpacDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="viewgetservicexpac"/> converted from <see cref="viewgetservicexpacDto"/>.</param>
        static partial void OnEntity(this viewgetservicexpacDto dto, viewgetservicexpac entity);

        /// <summary>
        /// Converts this instance of <see cref="viewgetservicexpacDto"/> to an instance of <see cref="viewgetservicexpac"/>.
        /// </summary>
        /// <param name="dto"><see cref="viewgetservicexpacDto"/> to convert.</param>
        public static viewgetservicexpac ToEntity(this viewgetservicexpacDto dto)
        {
            if (dto == null) return null;

            var entity = new viewgetservicexpac();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.PACIENTE = dto.PACIENTE;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.EDAD = dto.EDAD;
            entity.RUCCLI = dto.RUCCLI;
            entity.CLIENTE = dto.CLIENTE;
            entity.RUCFACT = dto.RUCFACT;
            entity.EMPFACT = dto.EMPFACT;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.PRECTOTAL = dto.PRECTOTAL;
            entity.Estado = dto.Estado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="viewgetservicexpac"/> to an instance of <see cref="viewgetservicexpacDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="viewgetservicexpac"/> to convert.</param>
        public static viewgetservicexpacDto ToDTO(this viewgetservicexpac entity)
        {
            if (entity == null) return null;

            var dto = new viewgetservicexpacDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.PACIENTE = entity.PACIENTE;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.EDAD = entity.EDAD;
            dto.RUCCLI = entity.RUCCLI;
            dto.CLIENTE = entity.CLIENTE;
            dto.RUCFACT = entity.RUCFACT;
            dto.EMPFACT = entity.EMPFACT;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.PRECTOTAL = entity.PRECTOTAL;
            dto.Estado = entity.Estado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="viewgetservicexpacDto"/> to an instance of <see cref="viewgetservicexpac"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<viewgetservicexpac> ToEntities(this IEnumerable<viewgetservicexpacDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="viewgetservicexpac"/> to an instance of <see cref="viewgetservicexpacDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<viewgetservicexpacDto> ToDTOs(this IEnumerable<viewgetservicexpac> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
