//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2020/07/24 - 14:16:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Server.WebClientAdmin.DAL;

namespace Sigesoft.Server.WebClientAdmin.BE
{

    /// <summary>
    /// Assembler for <see cref="viewresultadoswebx"/> and <see cref="viewresultadoswebxDto"/>.
    /// </summary>
    public static partial class viewresultadoswebxAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="viewresultadoswebxDto"/> converted from <see cref="viewresultadoswebx"/>.</param>
        static partial void OnDTO(this viewresultadoswebx entity, viewresultadoswebxDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="viewresultadoswebx"/> converted from <see cref="viewresultadoswebxDto"/>.</param>
        static partial void OnEntity(this viewresultadoswebxDto dto, viewresultadoswebx entity);

        /// <summary>
        /// Converts this instance of <see cref="viewresultadoswebxDto"/> to an instance of <see cref="viewresultadoswebx"/>.
        /// </summary>
        /// <param name="dto"><see cref="viewresultadoswebxDto"/> to convert.</param>
        public static viewresultadoswebx ToEntity(this viewresultadoswebxDto dto)
        {
            if (dto == null) return null;

            var entity = new viewresultadoswebx();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;
            entity.PACIENTE = dto.PACIENTE;
            entity.FECHA = dto.FECHA;
            entity.v_Name = dto.v_Name;
            entity.v_ProtocolId = dto.v_ProtocolId;
            entity.PROTOCOLO = dto.PROTOCOLO;
            entity.v_Value100 = dto.v_Value100;
            entity.v_Value200 = dto.v_Value200;
            entity.i_SystemUserId = dto.i_SystemUserId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="viewresultadoswebx"/> to an instance of <see cref="viewresultadoswebxDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="viewresultadoswebx"/> to convert.</param>
        public static viewresultadoswebxDto ToDTO(this viewresultadoswebx entity)
        {
            if (entity == null) return null;

            var dto = new viewresultadoswebxDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;
            dto.PACIENTE = entity.PACIENTE;
            dto.FECHA = entity.FECHA;
            dto.v_Name = entity.v_Name;
            dto.v_ProtocolId = entity.v_ProtocolId;
            dto.PROTOCOLO = entity.PROTOCOLO;
            dto.v_Value100 = entity.v_Value100;
            dto.v_Value200 = entity.v_Value200;
            dto.i_SystemUserId = entity.i_SystemUserId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="viewresultadoswebxDto"/> to an instance of <see cref="viewresultadoswebx"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<viewresultadoswebx> ToEntities(this IEnumerable<viewresultadoswebxDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="viewresultadoswebx"/> to an instance of <see cref="viewresultadoswebxDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<viewresultadoswebxDto> ToDTOs(this IEnumerable<viewresultadoswebx> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
