//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="background_comprar_registro_activoResult"/> and <see cref="background_comprar_registro_activoResultDto"/>.
    /// </summary>
    public static partial class background_comprar_registro_activoResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="background_comprar_registro_activoResultDto"/> converted from <see cref="background_comprar_registro_activoResult"/>.</param>
        static partial void OnDTO(this background_comprar_registro_activoResult entity, background_comprar_registro_activoResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="background_comprar_registro_activoResult"/> converted from <see cref="background_comprar_registro_activoResultDto"/>.</param>
        static partial void OnEntity(this background_comprar_registro_activoResultDto dto, background_comprar_registro_activoResult entity);

        /// <summary>
        /// Converts this instance of <see cref="background_comprar_registro_activoResultDto"/> to an instance of <see cref="background_comprar_registro_activoResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="background_comprar_registro_activoResultDto"/> to convert.</param>
        public static background_comprar_registro_activoResult ToEntity(this background_comprar_registro_activoResultDto dto)
        {
            if (dto == null) return null;

            var entity = new background_comprar_registro_activoResult();

            entity.Id = dto.Id;
            entity.ModoIngreso = dto.ModoIngreso;
            entity.ViaIngreso = dto.ViaIngreso;
            entity.FechaIngreso = dto.FechaIngreso;
            entity.NombreCompleto = dto.NombreCompleto;
            entity.ApePaterno = dto.ApePaterno;
            entity.ApeMaterno = dto.ApeMaterno;
            entity.Dni = dto.Dni;
            entity.Edad = dto.Edad;
            entity.PuestoTrabajo = dto.PuestoTrabajo;
            entity.Celular = dto.Celular;
            entity.TelfReferencia = dto.TelfReferencia;
            entity.Email = dto.Email;
            entity.Direccion = dto.Direccion;
            entity.Sexo = dto.Sexo;
            entity.EmpresaId = dto.EmpresaId;
            entity.Empleadora = dto.Empleadora;
            entity.SedeId = dto.SedeId;
            entity.MedicoVigilaId = dto.MedicoVigilaId;
            entity.EstadoClinicoId = dto.EstadoClinicoId;
            entity.ComentarioAlta = dto.ComentarioAlta;
            entity.NombreContacto = dto.NombreContacto;
            entity.TipoContacto = dto.TipoContacto;
            entity.NotificacionIngreso = dto.NotificacionIngreso;
            entity.Eliminado = dto.Eliminado;
            entity.UsuarioIngresa = dto.UsuarioIngresa;
            entity.FechaIngresa = dto.FechaIngresa;
            entity.UsuarioActualiza = dto.UsuarioActualiza;
            entity.FechaActualiza = dto.FechaActualiza;
            entity.Recetamedica = dto.Recetamedica;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="background_comprar_registro_activoResult"/> to an instance of <see cref="background_comprar_registro_activoResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="background_comprar_registro_activoResult"/> to convert.</param>
        public static background_comprar_registro_activoResultDto ToDTO(this background_comprar_registro_activoResult entity)
        {
            if (entity == null) return null;

            var dto = new background_comprar_registro_activoResultDto();

            dto.Id = entity.Id;
            dto.ModoIngreso = entity.ModoIngreso;
            dto.ViaIngreso = entity.ViaIngreso;
            dto.FechaIngreso = entity.FechaIngreso;
            dto.NombreCompleto = entity.NombreCompleto;
            dto.ApePaterno = entity.ApePaterno;
            dto.ApeMaterno = entity.ApeMaterno;
            dto.Dni = entity.Dni;
            dto.Edad = entity.Edad;
            dto.PuestoTrabajo = entity.PuestoTrabajo;
            dto.Celular = entity.Celular;
            dto.TelfReferencia = entity.TelfReferencia;
            dto.Email = entity.Email;
            dto.Direccion = entity.Direccion;
            dto.Sexo = entity.Sexo;
            dto.EmpresaId = entity.EmpresaId;
            dto.Empleadora = entity.Empleadora;
            dto.SedeId = entity.SedeId;
            dto.MedicoVigilaId = entity.MedicoVigilaId;
            dto.EstadoClinicoId = entity.EstadoClinicoId;
            dto.ComentarioAlta = entity.ComentarioAlta;
            dto.NombreContacto = entity.NombreContacto;
            dto.TipoContacto = entity.TipoContacto;
            dto.NotificacionIngreso = entity.NotificacionIngreso;
            dto.Eliminado = entity.Eliminado;
            dto.UsuarioIngresa = entity.UsuarioIngresa;
            dto.FechaIngresa = entity.FechaIngresa;
            dto.UsuarioActualiza = entity.UsuarioActualiza;
            dto.FechaActualiza = entity.FechaActualiza;
            dto.Recetamedica = entity.Recetamedica;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="background_comprar_registro_activoResultDto"/> to an instance of <see cref="background_comprar_registro_activoResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<background_comprar_registro_activoResult> ToEntities(this IEnumerable<background_comprar_registro_activoResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="background_comprar_registro_activoResult"/> to an instance of <see cref="background_comprar_registro_activoResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<background_comprar_registro_activoResultDto> ToDTOs(this IEnumerable<background_comprar_registro_activoResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
