//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:29
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="brand"/> and <see cref="brandDto"/>.
    /// </summary>
    public static partial class brandAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="brandDto"/> converted from <see cref="brand"/>.</param>
        static partial void OnDTO(this brand entity, brandDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="brand"/> converted from <see cref="brandDto"/>.</param>
        static partial void OnEntity(this brandDto dto, brand entity);

        /// <summary>
        /// Converts this instance of <see cref="brandDto"/> to an instance of <see cref="brand"/>.
        /// </summary>
        /// <param name="dto"><see cref="brandDto"/> to convert.</param>
        public static brand ToEntity(this brandDto dto)
        {
            if (dto == null) return null;

            var entity = new brand();

            entity.iBrandId = dto.iBrandId;
            entity.vBrandName = dto.vBrandName;
            entity.iBrandState = dto.iBrandState;
            entity.iDeleted = dto.iDeleted;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="brand"/> to an instance of <see cref="brandDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="brand"/> to convert.</param>
        public static brandDto ToDTO(this brand entity)
        {
            if (entity == null) return null;

            var dto = new brandDto();

            dto.iBrandId = entity.iBrandId;
            dto.vBrandName = entity.vBrandName;
            dto.iBrandState = entity.iBrandState;
            dto.iDeleted = entity.iDeleted;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="brandDto"/> to an instance of <see cref="brand"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<brand> ToEntities(this IEnumerable<brandDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="brand"/> to an instance of <see cref="brandDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<brandDto> ToDTOs(this IEnumerable<brand> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
