//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="buscar_pacienteResult"/> and <see cref="buscar_pacienteResultDto"/>.
    /// </summary>
    public static partial class buscar_pacienteResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="buscar_pacienteResultDto"/> converted from <see cref="buscar_pacienteResult"/>.</param>
        static partial void OnDTO(this buscar_pacienteResult entity, buscar_pacienteResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="buscar_pacienteResult"/> converted from <see cref="buscar_pacienteResultDto"/>.</param>
        static partial void OnEntity(this buscar_pacienteResultDto dto, buscar_pacienteResult entity);

        /// <summary>
        /// Converts this instance of <see cref="buscar_pacienteResultDto"/> to an instance of <see cref="buscar_pacienteResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="buscar_pacienteResultDto"/> to convert.</param>
        public static buscar_pacienteResult ToEntity(this buscar_pacienteResultDto dto)
        {
            if (dto == null) return null;

            var entity = new buscar_pacienteResult();

            entity.v_FirstName = dto.v_FirstName;
            entity.v_FirstLastName = dto.v_FirstLastName;
            entity.v_SecondLastName = dto.v_SecondLastName;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.i_ServiceStatusId = dto.i_ServiceStatusId;
            entity.v_Value1 = dto.v_Value1;
            entity.i_AptitudeStatusId = dto.i_AptitudeStatusId;
            entity.v_Value11 = dto.v_Value11;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="buscar_pacienteResult"/> to an instance of <see cref="buscar_pacienteResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="buscar_pacienteResult"/> to convert.</param>
        public static buscar_pacienteResultDto ToDTO(this buscar_pacienteResult entity)
        {
            if (entity == null) return null;

            var dto = new buscar_pacienteResultDto();

            dto.v_FirstName = entity.v_FirstName;
            dto.v_FirstLastName = entity.v_FirstLastName;
            dto.v_SecondLastName = entity.v_SecondLastName;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.i_ServiceStatusId = entity.i_ServiceStatusId;
            dto.v_Value1 = entity.v_Value1;
            dto.i_AptitudeStatusId = entity.i_AptitudeStatusId;
            dto.v_Value11 = entity.v_Value11;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="buscar_pacienteResultDto"/> to an instance of <see cref="buscar_pacienteResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<buscar_pacienteResult> ToEntities(this IEnumerable<buscar_pacienteResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="buscar_pacienteResult"/> to an instance of <see cref="buscar_pacienteResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<buscar_pacienteResultDto> ToDTOs(this IEnumerable<buscar_pacienteResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
