//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="drz_bs300readResult"/> and <see cref="drz_bs300readResultDto"/>.
    /// </summary>
    public static partial class drz_bs300readResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="drz_bs300readResultDto"/> converted from <see cref="drz_bs300readResult"/>.</param>
        static partial void OnDTO(this drz_bs300readResult entity, drz_bs300readResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="drz_bs300readResult"/> converted from <see cref="drz_bs300readResultDto"/>.</param>
        static partial void OnEntity(this drz_bs300readResultDto dto, drz_bs300readResult entity);

        /// <summary>
        /// Converts this instance of <see cref="drz_bs300readResultDto"/> to an instance of <see cref="drz_bs300readResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="drz_bs300readResultDto"/> to convert.</param>
        public static drz_bs300readResult ToEntity(this drz_bs300readResultDto dto)
        {
            if (dto == null) return null;

            var entity = new drz_bs300readResult();

            entity.nombrePerson = dto.nombrePerson;
            entity.d_Birthdate = dto.d_Birthdate;
            entity.i_SexTypeId = dto.i_SexTypeId;
            entity.v_ComponentFieldId = dto.v_ComponentFieldId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="drz_bs300readResult"/> to an instance of <see cref="drz_bs300readResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="drz_bs300readResult"/> to convert.</param>
        public static drz_bs300readResultDto ToDTO(this drz_bs300readResult entity)
        {
            if (entity == null) return null;

            var dto = new drz_bs300readResultDto();

            dto.nombrePerson = entity.nombrePerson;
            dto.d_Birthdate = entity.d_Birthdate;
            dto.i_SexTypeId = entity.i_SexTypeId;
            dto.v_ComponentFieldId = entity.v_ComponentFieldId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="drz_bs300readResultDto"/> to an instance of <see cref="drz_bs300readResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<drz_bs300readResult> ToEntities(this IEnumerable<drz_bs300readResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="drz_bs300readResult"/> to an instance of <see cref="drz_bs300readResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<drz_bs300readResultDto> ToDTOs(this IEnumerable<drz_bs300readResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
