//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="employee"/> and <see cref="employeeDto"/>.
    /// </summary>
    public static partial class employeeAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="employeeDto"/> converted from <see cref="employee"/>.</param>
        static partial void OnDTO(this employee entity, employeeDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="employee"/> converted from <see cref="employeeDto"/>.</param>
        static partial void OnEntity(this employeeDto dto, employee entity);

        /// <summary>
        /// Converts this instance of <see cref="employeeDto"/> to an instance of <see cref="employee"/>.
        /// </summary>
        /// <param name="dto"><see cref="employeeDto"/> to convert.</param>
        public static employee ToEntity(this employeeDto dto)
        {
            if (dto == null) return null;

            var entity = new employee();

            entity.EmployeeId = dto.EmployeeId;
            entity.IdentificationType = dto.IdentificationType;
            entity.NationalIDNumber = dto.NationalIDNumber;
            entity.Gender = dto.Gender;
            entity.FirstName = dto.FirstName;
            entity.MiddleName = dto.MiddleName;
            entity.LastName = dto.LastName;
            entity.BirthDate = dto.BirthDate;
            entity.EmailAddress = dto.EmailAddress;
            entity.Job = dto.Job;
            entity.AddressLine1 = dto.AddressLine1;
            entity.Hire = dto.Hire;
            entity.Headquarter = dto.Headquarter;
            entity.Employer = dto.Employer;
            entity.ProcessedData = dto.ProcessedData;
            entity.CurrentFlag = dto.CurrentFlag;
            entity.rowguid = dto.rowguid;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="employee"/> to an instance of <see cref="employeeDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="employee"/> to convert.</param>
        public static employeeDto ToDTO(this employee entity)
        {
            if (entity == null) return null;

            var dto = new employeeDto();

            dto.EmployeeId = entity.EmployeeId;
            dto.IdentificationType = entity.IdentificationType;
            dto.NationalIDNumber = entity.NationalIDNumber;
            dto.Gender = entity.Gender;
            dto.FirstName = entity.FirstName;
            dto.MiddleName = entity.MiddleName;
            dto.LastName = entity.LastName;
            dto.BirthDate = entity.BirthDate;
            dto.EmailAddress = entity.EmailAddress;
            dto.Job = entity.Job;
            dto.AddressLine1 = entity.AddressLine1;
            dto.Hire = entity.Hire;
            dto.Headquarter = entity.Headquarter;
            dto.Employer = entity.Employer;
            dto.ProcessedData = entity.ProcessedData;
            dto.CurrentFlag = entity.CurrentFlag;
            dto.rowguid = entity.rowguid;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="employeeDto"/> to an instance of <see cref="employee"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<employee> ToEntities(this IEnumerable<employeeDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="employee"/> to an instance of <see cref="employeeDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<employeeDto> ToDTOs(this IEnumerable<employee> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
