//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:22
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="getpositivoscovidResult"/> and <see cref="getpositivoscovidResultDto"/>.
    /// </summary>
    public static partial class getpositivoscovidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="getpositivoscovidResultDto"/> converted from <see cref="getpositivoscovidResult"/>.</param>
        static partial void OnDTO(this getpositivoscovidResult entity, getpositivoscovidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="getpositivoscovidResult"/> converted from <see cref="getpositivoscovidResultDto"/>.</param>
        static partial void OnEntity(this getpositivoscovidResultDto dto, getpositivoscovidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="getpositivoscovidResultDto"/> to an instance of <see cref="getpositivoscovidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="getpositivoscovidResultDto"/> to convert.</param>
        public static getpositivoscovidResult ToEntity(this getpositivoscovidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new getpositivoscovidResult();

            entity.ServiceId = dto.ServiceId;
            entity.ComponentId = dto.ComponentId;
            entity.ServiceComponentId = dto.ServiceComponentId;
            entity.ComponentFieldId = dto.ComponentFieldId;
            entity.Value1 = dto.Value1;
            entity.Fecha = dto.Fecha;
            entity.Empleador = dto.Empleador;
            entity.Empresa_principal = dto.Empresa_principal;
            entity.ProtocolName = dto.ProtocolName;
            entity.Tipo_documento = dto.Tipo_documento;
            entity.Nro_documento = dto.Nro_documento;
            entity.ApellidoPaterno = dto.ApellidoPaterno;
            entity.ApellidoMaterno = dto.ApellidoMaterno;
            entity.Nombres = dto.Nombres;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.Sexo = dto.Sexo;
            entity.Celular = dto.Celular;
            entity.Otro_telefono = dto.Otro_telefono;
            entity.Ubigeo = dto.Ubigeo;
            entity.Aptitud = dto.Aptitud;
            entity.Tecnico = dto.Tecnico;
            entity.Sede = dto.Sede;
            entity.Edad = dto.Edad;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="getpositivoscovidResult"/> to an instance of <see cref="getpositivoscovidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="getpositivoscovidResult"/> to convert.</param>
        public static getpositivoscovidResultDto ToDTO(this getpositivoscovidResult entity)
        {
            if (entity == null) return null;

            var dto = new getpositivoscovidResultDto();

            dto.ServiceId = entity.ServiceId;
            dto.ComponentId = entity.ComponentId;
            dto.ServiceComponentId = entity.ServiceComponentId;
            dto.ComponentFieldId = entity.ComponentFieldId;
            dto.Value1 = entity.Value1;
            dto.Fecha = entity.Fecha;
            dto.Empleador = entity.Empleador;
            dto.Empresa_principal = entity.Empresa_principal;
            dto.ProtocolName = entity.ProtocolName;
            dto.Tipo_documento = entity.Tipo_documento;
            dto.Nro_documento = entity.Nro_documento;
            dto.ApellidoPaterno = entity.ApellidoPaterno;
            dto.ApellidoMaterno = entity.ApellidoMaterno;
            dto.Nombres = entity.Nombres;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.Sexo = entity.Sexo;
            dto.Celular = entity.Celular;
            dto.Otro_telefono = entity.Otro_telefono;
            dto.Ubigeo = entity.Ubigeo;
            dto.Aptitud = entity.Aptitud;
            dto.Tecnico = entity.Tecnico;
            dto.Sede = entity.Sede;
            dto.Edad = entity.Edad;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="getpositivoscovidResultDto"/> to an instance of <see cref="getpositivoscovidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<getpositivoscovidResult> ToEntities(this IEnumerable<getpositivoscovidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="getpositivoscovidResult"/> to an instance of <see cref="getpositivoscovidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<getpositivoscovidResultDto> ToDTOs(this IEnumerable<getpositivoscovidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
