//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:33
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="hcactualizado"/> and <see cref="hcactualizadoDto"/>.
    /// </summary>
    public static partial class hcactualizadoAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="hcactualizadoDto"/> converted from <see cref="hcactualizado"/>.</param>
        static partial void OnDTO(this hcactualizado entity, hcactualizadoDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="hcactualizado"/> converted from <see cref="hcactualizadoDto"/>.</param>
        static partial void OnEntity(this hcactualizadoDto dto, hcactualizado entity);

        /// <summary>
        /// Converts this instance of <see cref="hcactualizadoDto"/> to an instance of <see cref="hcactualizado"/>.
        /// </summary>
        /// <param name="dto"><see cref="hcactualizadoDto"/> to convert.</param>
        public static hcactualizado ToEntity(this hcactualizadoDto dto)
        {
            if (dto == null) return null;

            var entity = new hcactualizado();

            entity.i_HcActualizadoId = dto.i_HcActualizadoId;
            entity.HC = dto.HC;
            entity.EmpresaEmpleadora = dto.EmpresaEmpleadora;
            entity.ApellidoPaterno = dto.ApellidoPaterno;
            entity.ApellidoMaterno = dto.ApellidoMaterno;
            entity.Nombres = dto.Nombres;
            entity.Dni = dto.Dni;
            entity.Sexo = dto.Sexo;
            entity.Sede = dto.Sede;
            entity.Puesto = dto.Puesto;
            entity.Area = dto.Area;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.SedeId = dto.SedeId;
            entity.SexoId = dto.SexoId;
            entity.HcId = dto.HcId;
            entity.FechaActualizacion = dto.FechaActualizacion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="hcactualizado"/> to an instance of <see cref="hcactualizadoDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="hcactualizado"/> to convert.</param>
        public static hcactualizadoDto ToDTO(this hcactualizado entity)
        {
            if (entity == null) return null;

            var dto = new hcactualizadoDto();

            dto.i_HcActualizadoId = entity.i_HcActualizadoId;
            dto.HC = entity.HC;
            dto.EmpresaEmpleadora = entity.EmpresaEmpleadora;
            dto.ApellidoPaterno = entity.ApellidoPaterno;
            dto.ApellidoMaterno = entity.ApellidoMaterno;
            dto.Nombres = entity.Nombres;
            dto.Dni = entity.Dni;
            dto.Sexo = entity.Sexo;
            dto.Sede = entity.Sede;
            dto.Puesto = entity.Puesto;
            dto.Area = entity.Area;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.SedeId = entity.SedeId;
            dto.SexoId = entity.SexoId;
            dto.HcId = entity.HcId;
            dto.FechaActualizacion = entity.FechaActualizacion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="hcactualizadoDto"/> to an instance of <see cref="hcactualizado"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<hcactualizado> ToEntities(this IEnumerable<hcactualizadoDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="hcactualizado"/> to an instance of <see cref="hcactualizadoDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<hcactualizadoDto> ToDTOs(this IEnumerable<hcactualizado> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
