//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="obteneragendaporcategoriaResult"/> and <see cref="obteneragendaporcategoriaResultDto"/>.
    /// </summary>
    public static partial class obteneragendaporcategoriaResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obteneragendaporcategoriaResultDto"/> converted from <see cref="obteneragendaporcategoriaResult"/>.</param>
        static partial void OnDTO(this obteneragendaporcategoriaResult entity, obteneragendaporcategoriaResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obteneragendaporcategoriaResult"/> converted from <see cref="obteneragendaporcategoriaResultDto"/>.</param>
        static partial void OnEntity(this obteneragendaporcategoriaResultDto dto, obteneragendaporcategoriaResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obteneragendaporcategoriaResultDto"/> to an instance of <see cref="obteneragendaporcategoriaResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obteneragendaporcategoriaResultDto"/> to convert.</param>
        public static obteneragendaporcategoriaResult ToEntity(this obteneragendaporcategoriaResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obteneragendaporcategoriaResult();

            entity.i_NroTickets = dto.i_NroTickets;
            entity.d_CircuitStartDate = dto.d_CircuitStartDate;
            entity.Paciente = dto.Paciente;
            entity.NroDocum = dto.NroDocum;
            entity.Edad = dto.Edad;
            entity.Empleador = dto.Empleador;
            entity.Cliente = dto.Cliente;
            entity.Protocolo = dto.Protocolo;
            entity.v_Value1 = dto.v_Value1;
            entity.v_CurrentOccupation = dto.v_CurrentOccupation;
            entity.i_IsVipId = dto.i_IsVipId;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.v_PersonId = dto.v_PersonId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obteneragendaporcategoriaResult"/> to an instance of <see cref="obteneragendaporcategoriaResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obteneragendaporcategoriaResult"/> to convert.</param>
        public static obteneragendaporcategoriaResultDto ToDTO(this obteneragendaporcategoriaResult entity)
        {
            if (entity == null) return null;

            var dto = new obteneragendaporcategoriaResultDto();

            dto.i_NroTickets = entity.i_NroTickets;
            dto.d_CircuitStartDate = entity.d_CircuitStartDate;
            dto.Paciente = entity.Paciente;
            dto.NroDocum = entity.NroDocum;
            dto.Edad = entity.Edad;
            dto.Empleador = entity.Empleador;
            dto.Cliente = entity.Cliente;
            dto.Protocolo = entity.Protocolo;
            dto.v_Value1 = entity.v_Value1;
            dto.v_CurrentOccupation = entity.v_CurrentOccupation;
            dto.i_IsVipId = entity.i_IsVipId;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.v_PersonId = entity.v_PersonId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obteneragendaporcategoriaResultDto"/> to an instance of <see cref="obteneragendaporcategoriaResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obteneragendaporcategoriaResult> ToEntities(this IEnumerable<obteneragendaporcategoriaResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obteneragendaporcategoriaResult"/> to an instance of <see cref="obteneragendaporcategoriaResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obteneragendaporcategoriaResultDto> ToDTOs(this IEnumerable<obteneragendaporcategoriaResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
