//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="obtenerhojatrabajolabResult"/> and <see cref="obtenerhojatrabajolabResultDto"/>.
    /// </summary>
    public static partial class obtenerhojatrabajolabResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="obtenerhojatrabajolabResultDto"/> converted from <see cref="obtenerhojatrabajolabResult"/>.</param>
        static partial void OnDTO(this obtenerhojatrabajolabResult entity, obtenerhojatrabajolabResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="obtenerhojatrabajolabResult"/> converted from <see cref="obtenerhojatrabajolabResultDto"/>.</param>
        static partial void OnEntity(this obtenerhojatrabajolabResultDto dto, obtenerhojatrabajolabResult entity);

        /// <summary>
        /// Converts this instance of <see cref="obtenerhojatrabajolabResultDto"/> to an instance of <see cref="obtenerhojatrabajolabResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="obtenerhojatrabajolabResultDto"/> to convert.</param>
        public static obtenerhojatrabajolabResult ToEntity(this obtenerhojatrabajolabResultDto dto)
        {
            if (dto == null) return null;

            var entity = new obtenerhojatrabajolabResult();

            entity.ID = dto.ID;
            entity.column1 = dto.column1;
            entity.EDAD = dto.EDAD;
            entity.SEXO = dto.SEXO;
            entity.NOMBRE = dto.NOMBRE;
            entity.GRUPO = dto.GRUPO;
            entity.C = dto.C;
            entity.PH = dto.PH;
            entity.D = dto.D;
            entity.BQ = dto.BQ;
            entity.CEL = dto.CEL;
            entity.LEU = dto.LEU;
            entity.HEM = dto.HEM;
            entity.OBS = dto.OBS;
            entity.P_ = dto.P_;
            entity.P_1 = dto.P_1;
            entity.P_2 = dto.P_2;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="obtenerhojatrabajolabResult"/> to an instance of <see cref="obtenerhojatrabajolabResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="obtenerhojatrabajolabResult"/> to convert.</param>
        public static obtenerhojatrabajolabResultDto ToDTO(this obtenerhojatrabajolabResult entity)
        {
            if (entity == null) return null;

            var dto = new obtenerhojatrabajolabResultDto();

            dto.ID = entity.ID;
            dto.column1 = entity.column1;
            dto.EDAD = entity.EDAD;
            dto.SEXO = entity.SEXO;
            dto.NOMBRE = entity.NOMBRE;
            dto.GRUPO = entity.GRUPO;
            dto.C = entity.C;
            dto.PH = entity.PH;
            dto.D = entity.D;
            dto.BQ = entity.BQ;
            dto.CEL = entity.CEL;
            dto.LEU = entity.LEU;
            dto.HEM = entity.HEM;
            dto.OBS = entity.OBS;
            dto.P_ = entity.P_;
            dto.P_1 = entity.P_1;
            dto.P_2 = entity.P_2;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerhojatrabajolabResultDto"/> to an instance of <see cref="obtenerhojatrabajolabResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<obtenerhojatrabajolabResult> ToEntities(this IEnumerable<obtenerhojatrabajolabResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="obtenerhojatrabajolabResult"/> to an instance of <see cref="obtenerhojatrabajolabResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<obtenerhojatrabajolabResultDto> ToDTOs(this IEnumerable<obtenerhojatrabajolabResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
