//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_servicios_listadoResult"/> and <see cref="regcovid_servicios_listadoResultDto"/>.
    /// </summary>
    public static partial class regcovid_servicios_listadoResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_servicios_listadoResultDto"/> converted from <see cref="regcovid_servicios_listadoResult"/>.</param>
        static partial void OnDTO(this regcovid_servicios_listadoResult entity, regcovid_servicios_listadoResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_servicios_listadoResult"/> converted from <see cref="regcovid_servicios_listadoResultDto"/>.</param>
        static partial void OnEntity(this regcovid_servicios_listadoResultDto dto, regcovid_servicios_listadoResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_servicios_listadoResultDto"/> to an instance of <see cref="regcovid_servicios_listadoResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_servicios_listadoResultDto"/> to convert.</param>
        public static regcovid_servicios_listadoResult ToEntity(this regcovid_servicios_listadoResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_servicios_listadoResult();

            entity.FechaHoraRegistro = dto.FechaHoraRegistro;
            entity.MedicalCenter = dto.MedicalCenter;
            entity.v_Sede = dto.v_Sede;
            entity.Trabajador = dto.Trabajador;
            entity.DNI = dto.DNI;
            entity.CELULAR = dto.CELULAR;
            entity.TecnicoCovid = dto.TecnicoCovid;
            entity.EDAD = dto.EDAD;
            entity.Resultado = dto.Resultado;
            entity.v_ServiceId = dto.v_ServiceId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_servicios_listadoResult"/> to an instance of <see cref="regcovid_servicios_listadoResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_servicios_listadoResult"/> to convert.</param>
        public static regcovid_servicios_listadoResultDto ToDTO(this regcovid_servicios_listadoResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_servicios_listadoResultDto();

            dto.FechaHoraRegistro = entity.FechaHoraRegistro;
            dto.MedicalCenter = entity.MedicalCenter;
            dto.v_Sede = entity.v_Sede;
            dto.Trabajador = entity.Trabajador;
            dto.DNI = entity.DNI;
            dto.CELULAR = entity.CELULAR;
            dto.TecnicoCovid = entity.TecnicoCovid;
            dto.EDAD = entity.EDAD;
            dto.Resultado = entity.Resultado;
            dto.v_ServiceId = entity.v_ServiceId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_servicios_listadoResultDto"/> to an instance of <see cref="regcovid_servicios_listadoResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_servicios_listadoResult> ToEntities(this IEnumerable<regcovid_servicios_listadoResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_servicios_listadoResult"/> to an instance of <see cref="regcovid_servicios_listadoResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_servicios_listadoResultDto> ToDTOs(this IEnumerable<regcovid_servicios_listadoResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
