//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_get_protocolidResult"/> and <see cref="regcovid_get_protocolidResultDto"/>.
    /// </summary>
    public static partial class regcovid_get_protocolidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_protocolidResultDto"/> converted from <see cref="regcovid_get_protocolidResult"/>.</param>
        static partial void OnDTO(this regcovid_get_protocolidResult entity, regcovid_get_protocolidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_protocolidResult"/> converted from <see cref="regcovid_get_protocolidResultDto"/>.</param>
        static partial void OnEntity(this regcovid_get_protocolidResultDto dto, regcovid_get_protocolidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_protocolidResultDto"/> to an instance of <see cref="regcovid_get_protocolidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_protocolidResultDto"/> to convert.</param>
        public static regcovid_get_protocolidResult ToEntity(this regcovid_get_protocolidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_get_protocolidResult();

            entity.ProtocolId = dto.ProtocolId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_protocolidResult"/> to an instance of <see cref="regcovid_get_protocolidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_protocolidResult"/> to convert.</param>
        public static regcovid_get_protocolidResultDto ToDTO(this regcovid_get_protocolidResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_get_protocolidResultDto();

            dto.ProtocolId = entity.ProtocolId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_protocolidResultDto"/> to an instance of <see cref="regcovid_get_protocolidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_get_protocolidResult> ToEntities(this IEnumerable<regcovid_get_protocolidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_protocolidResult"/> to an instance of <see cref="regcovid_get_protocolidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_get_protocolidResultDto> ToDTOs(this IEnumerable<regcovid_get_protocolidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
