//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_background_servicios_anterioresResult"/> and <see cref="regcovid_background_servicios_anterioresResultDto"/>.
    /// </summary>
    public static partial class regcovid_background_servicios_anterioresResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_background_servicios_anterioresResultDto"/> converted from <see cref="regcovid_background_servicios_anterioresResult"/>.</param>
        static partial void OnDTO(this regcovid_background_servicios_anterioresResult entity, regcovid_background_servicios_anterioresResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_background_servicios_anterioresResult"/> converted from <see cref="regcovid_background_servicios_anterioresResultDto"/>.</param>
        static partial void OnEntity(this regcovid_background_servicios_anterioresResultDto dto, regcovid_background_servicios_anterioresResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_background_servicios_anterioresResultDto"/> to an instance of <see cref="regcovid_background_servicios_anterioresResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_background_servicios_anterioresResultDto"/> to convert.</param>
        public static regcovid_background_servicios_anterioresResult ToEntity(this regcovid_background_servicios_anterioresResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_background_servicios_anterioresResult();

            entity.FechaHoraRegistro = dto.FechaHoraRegistro;
            entity.MedicalCenter = dto.MedicalCenter;
            entity.EmpresaEmpleadora = dto.EmpresaEmpleadora;
            entity.v_Sede = dto.v_Sede;
            entity.Trabajador = dto.Trabajador;
            entity.DNI = dto.DNI;
            entity.CELULAR = dto.CELULAR;
            entity.TecnicoCovid = dto.TecnicoCovid;
            entity.EDAD = dto.EDAD;
            entity.Resultado = dto.Resultado;
            entity.v_ServiceId = dto.v_ServiceId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_background_servicios_anterioresResult"/> to an instance of <see cref="regcovid_background_servicios_anterioresResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_background_servicios_anterioresResult"/> to convert.</param>
        public static regcovid_background_servicios_anterioresResultDto ToDTO(this regcovid_background_servicios_anterioresResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_background_servicios_anterioresResultDto();

            dto.FechaHoraRegistro = entity.FechaHoraRegistro;
            dto.MedicalCenter = entity.MedicalCenter;
            dto.EmpresaEmpleadora = entity.EmpresaEmpleadora;
            dto.v_Sede = entity.v_Sede;
            dto.Trabajador = entity.Trabajador;
            dto.DNI = entity.DNI;
            dto.CELULAR = entity.CELULAR;
            dto.TecnicoCovid = entity.TecnicoCovid;
            dto.EDAD = entity.EDAD;
            dto.Resultado = entity.Resultado;
            dto.v_ServiceId = entity.v_ServiceId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_background_servicios_anterioresResultDto"/> to an instance of <see cref="regcovid_background_servicios_anterioresResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_background_servicios_anterioresResult> ToEntities(this IEnumerable<regcovid_background_servicios_anterioresResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_background_servicios_anterioresResult"/> to an instance of <see cref="regcovid_background_servicios_anterioresResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_background_servicios_anterioresResultDto> ToDTOs(this IEnumerable<regcovid_background_servicios_anterioresResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
