//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_list_servicesResult"/> and <see cref="regcovid_list_servicesResultDto"/>.
    /// </summary>
    public static partial class regcovid_list_servicesResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_list_servicesResultDto"/> converted from <see cref="regcovid_list_servicesResult"/>.</param>
        static partial void OnDTO(this regcovid_list_servicesResult entity, regcovid_list_servicesResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_list_servicesResult"/> converted from <see cref="regcovid_list_servicesResultDto"/>.</param>
        static partial void OnEntity(this regcovid_list_servicesResultDto dto, regcovid_list_servicesResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_list_servicesResultDto"/> to an instance of <see cref="regcovid_list_servicesResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_list_servicesResultDto"/> to convert.</param>
        public static regcovid_list_servicesResult ToEntity(this regcovid_list_servicesResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_list_servicesResult();

            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.WorkerName = dto.WorkerName;
            entity.ProtocolName = dto.ProtocolName;
            entity.OrganizationName = dto.OrganizationName;
            entity.CurrentOccupation = dto.CurrentOccupation;
            entity.ServiceId = dto.ServiceId;
            entity.PersonId = dto.PersonId;
            entity.ComponentId = dto.ComponentId;
            entity.IIndex = dto.IIndex;
            entity.OrganizationId = dto.OrganizationId;
            entity.TelephoneNumber = dto.TelephoneNumber;
            entity.ServiceComponentId = dto.ServiceComponentId;
            entity.EncuestaCulminada = dto.EncuestaCulminada;
            entity.LaboratorioCulminada = dto.LaboratorioCulminada;
            entity.ClinicaExternad = dto.ClinicaExternad;
            entity.MedicalCenter = dto.MedicalCenter;
            entity.TypeExam = dto.TypeExam;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_list_servicesResult"/> to an instance of <see cref="regcovid_list_servicesResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_list_servicesResult"/> to convert.</param>
        public static regcovid_list_servicesResultDto ToDTO(this regcovid_list_servicesResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_list_servicesResultDto();

            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.WorkerName = entity.WorkerName;
            dto.ProtocolName = entity.ProtocolName;
            dto.OrganizationName = entity.OrganizationName;
            dto.CurrentOccupation = entity.CurrentOccupation;
            dto.ServiceId = entity.ServiceId;
            dto.PersonId = entity.PersonId;
            dto.ComponentId = entity.ComponentId;
            dto.IIndex = entity.IIndex;
            dto.OrganizationId = entity.OrganizationId;
            dto.TelephoneNumber = entity.TelephoneNumber;
            dto.ServiceComponentId = entity.ServiceComponentId;
            dto.EncuestaCulminada = entity.EncuestaCulminada;
            dto.LaboratorioCulminada = entity.LaboratorioCulminada;
            dto.ClinicaExternad = entity.ClinicaExternad;
            dto.MedicalCenter = entity.MedicalCenter;
            dto.TypeExam = entity.TypeExam;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_list_servicesResultDto"/> to an instance of <see cref="regcovid_list_servicesResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_list_servicesResult> ToEntities(this IEnumerable<regcovid_list_servicesResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_list_servicesResult"/> to an instance of <see cref="regcovid_list_servicesResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_list_servicesResultDto> ToDTOs(this IEnumerable<regcovid_list_servicesResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
