//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_get_worker_from_hcactualizadoResult"/> and <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/>.
    /// </summary>
    public static partial class regcovid_get_worker_from_hcactualizadoResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_worker_from_hcactualizadoResultDto"/> converted from <see cref="regcovid_get_worker_from_hcactualizadoResult"/>.</param>
        static partial void OnDTO(this regcovid_get_worker_from_hcactualizadoResult entity, regcovid_get_worker_from_hcactualizadoResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_worker_from_hcactualizadoResult"/> converted from <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/>.</param>
        static partial void OnEntity(this regcovid_get_worker_from_hcactualizadoResultDto dto, regcovid_get_worker_from_hcactualizadoResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/> to an instance of <see cref="regcovid_get_worker_from_hcactualizadoResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_worker_from_hcactualizadoResultDto"/> to convert.</param>
        public static regcovid_get_worker_from_hcactualizadoResult ToEntity(this regcovid_get_worker_from_hcactualizadoResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_get_worker_from_hcactualizadoResult();

            entity.Filtro = dto.Filtro;
            entity.HcActualizadoId = dto.HcActualizadoId;
            entity.HC = dto.HC;
            entity.EmpresaEmpleadora = dto.EmpresaEmpleadora;
            entity.ApellidoPaterno = dto.ApellidoPaterno;
            entity.ApellidoMaterno = dto.ApellidoMaterno;
            entity.Nombres = dto.Nombres;
            entity.Dni = dto.Dni;
            entity.Sexo = dto.Sexo;
            entity.Sede = dto.Sede;
            entity.SedeId = dto.SedeId;
            entity.Puesto = dto.Puesto;
            entity.FechaNacimiento = dto.FechaNacimiento;
            entity.SexoId = dto.SexoId;
            entity.HcId = dto.HcId;
            entity.Telefono = dto.Telefono;
            entity.Email = dto.Email;
            entity.Direccion = dto.Direccion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_worker_from_hcactualizadoResult"/> to an instance of <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_worker_from_hcactualizadoResult"/> to convert.</param>
        public static regcovid_get_worker_from_hcactualizadoResultDto ToDTO(this regcovid_get_worker_from_hcactualizadoResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_get_worker_from_hcactualizadoResultDto();

            dto.Filtro = entity.Filtro;
            dto.HcActualizadoId = entity.HcActualizadoId;
            dto.HC = entity.HC;
            dto.EmpresaEmpleadora = entity.EmpresaEmpleadora;
            dto.ApellidoPaterno = entity.ApellidoPaterno;
            dto.ApellidoMaterno = entity.ApellidoMaterno;
            dto.Nombres = entity.Nombres;
            dto.Dni = entity.Dni;
            dto.Sexo = entity.Sexo;
            dto.Sede = entity.Sede;
            dto.SedeId = entity.SedeId;
            dto.Puesto = entity.Puesto;
            dto.FechaNacimiento = entity.FechaNacimiento;
            dto.SexoId = entity.SexoId;
            dto.HcId = entity.HcId;
            dto.Telefono = entity.Telefono;
            dto.Email = entity.Email;
            dto.Direccion = entity.Direccion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/> to an instance of <see cref="regcovid_get_worker_from_hcactualizadoResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_get_worker_from_hcactualizadoResult> ToEntities(this IEnumerable<regcovid_get_worker_from_hcactualizadoResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_worker_from_hcactualizadoResult"/> to an instance of <see cref="regcovid_get_worker_from_hcactualizadoResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_get_worker_from_hcactualizadoResultDto> ToDTOs(this IEnumerable<regcovid_get_worker_from_hcactualizadoResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
