//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/> and <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/>.
    /// </summary>
    public static partial class regcovid_positivosenviadosreg_vs_positivosrecividosvigResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/> converted from <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/>.</param>
        static partial void OnDTO(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult entity, regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/> converted from <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/>.</param>
        static partial void OnEntity(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto dto, regcovid_positivosenviadosreg_vs_positivosrecividosvigResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/> to convert.</param>
        public static regcovid_positivosenviadosreg_vs_positivosrecividosvigResult ToEntity(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_positivosenviadosreg_vs_positivosrecividosvigResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.Nombres = dto.Nombres;
            entity.TecnicoCovid = dto.TecnicoCovid;
            entity.ComponentFieldId = dto.ComponentFieldId;
            entity.ServiceComponentFieldsId = dto.ServiceComponentFieldsId;
            entity.Value1 = dto.Value1;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/> to convert.</param>
        public static regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto ToDTO(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.Nombres = entity.Nombres;
            dto.TecnicoCovid = entity.TecnicoCovid;
            dto.ComponentFieldId = entity.ComponentFieldId;
            dto.ServiceComponentFieldsId = entity.ServiceComponentFieldsId;
            dto.Value1 = entity.Value1;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult> ToEntities(this IEnumerable<regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_positivosenviadosreg_vs_positivosrecividosvigResultDto> ToDTOs(this IEnumerable<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
