//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:23
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_get_empresas_empleadorasResult"/> and <see cref="regcovid_get_empresas_empleadorasResultDto"/>.
    /// </summary>
    public static partial class regcovid_get_empresas_empleadorasResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_empresas_empleadorasResultDto"/> converted from <see cref="regcovid_get_empresas_empleadorasResult"/>.</param>
        static partial void OnDTO(this regcovid_get_empresas_empleadorasResult entity, regcovid_get_empresas_empleadorasResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_empresas_empleadorasResult"/> converted from <see cref="regcovid_get_empresas_empleadorasResultDto"/>.</param>
        static partial void OnEntity(this regcovid_get_empresas_empleadorasResultDto dto, regcovid_get_empresas_empleadorasResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_empresas_empleadorasResultDto"/> to an instance of <see cref="regcovid_get_empresas_empleadorasResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_empresas_empleadorasResultDto"/> to convert.</param>
        public static regcovid_get_empresas_empleadorasResult ToEntity(this regcovid_get_empresas_empleadorasResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_get_empresas_empleadorasResult();

            entity.EmpresaEmpleadoraId = dto.EmpresaEmpleadoraId;
            entity.Nombre = dto.Nombre;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_empresas_empleadorasResult"/> to an instance of <see cref="regcovid_get_empresas_empleadorasResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_empresas_empleadorasResult"/> to convert.</param>
        public static regcovid_get_empresas_empleadorasResultDto ToDTO(this regcovid_get_empresas_empleadorasResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_get_empresas_empleadorasResultDto();

            dto.EmpresaEmpleadoraId = entity.EmpresaEmpleadoraId;
            dto.Nombre = entity.Nombre;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_empresas_empleadorasResultDto"/> to an instance of <see cref="regcovid_get_empresas_empleadorasResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_get_empresas_empleadorasResult> ToEntities(this IEnumerable<regcovid_get_empresas_empleadorasResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_empresas_empleadorasResult"/> to an instance of <see cref="regcovid_get_empresas_empleadorasResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_get_empresas_empleadorasResultDto> ToDTOs(this IEnumerable<regcovid_get_empresas_empleadorasResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
