//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_select_testdeviceResult"/> and <see cref="regcovid_select_testdeviceResultDto"/>.
    /// </summary>
    public static partial class regcovid_select_testdeviceResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_select_testdeviceResultDto"/> converted from <see cref="regcovid_select_testdeviceResult"/>.</param>
        static partial void OnDTO(this regcovid_select_testdeviceResult entity, regcovid_select_testdeviceResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_select_testdeviceResult"/> converted from <see cref="regcovid_select_testdeviceResultDto"/>.</param>
        static partial void OnEntity(this regcovid_select_testdeviceResultDto dto, regcovid_select_testdeviceResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_select_testdeviceResultDto"/> to an instance of <see cref="regcovid_select_testdeviceResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_select_testdeviceResultDto"/> to convert.</param>
        public static regcovid_select_testdeviceResult ToEntity(this regcovid_select_testdeviceResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_select_testdeviceResult();

            entity.iTestDeviceId = dto.iTestDeviceId;
            entity.vTestDeviceName = dto.vTestDeviceName;
            entity.vTestDeviceDescription = dto.vTestDeviceDescription;
            entity.iTestDeviceIdBrand = dto.iTestDeviceIdBrand;
            entity.vTestDeviceLot = dto.vTestDeviceLot;
            entity.dTestDeviceDueDate = dto.dTestDeviceDueDate;
            entity.iTestDeviceState = dto.iTestDeviceState;
            entity.iDeleted = dto.iDeleted;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_select_testdeviceResult"/> to an instance of <see cref="regcovid_select_testdeviceResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_select_testdeviceResult"/> to convert.</param>
        public static regcovid_select_testdeviceResultDto ToDTO(this regcovid_select_testdeviceResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_select_testdeviceResultDto();

            dto.iTestDeviceId = entity.iTestDeviceId;
            dto.vTestDeviceName = entity.vTestDeviceName;
            dto.vTestDeviceDescription = entity.vTestDeviceDescription;
            dto.iTestDeviceIdBrand = entity.iTestDeviceIdBrand;
            dto.vTestDeviceLot = entity.vTestDeviceLot;
            dto.dTestDeviceDueDate = entity.dTestDeviceDueDate;
            dto.iTestDeviceState = entity.iTestDeviceState;
            dto.iDeleted = entity.iDeleted;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_select_testdeviceResultDto"/> to an instance of <see cref="regcovid_select_testdeviceResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_select_testdeviceResult> ToEntities(this IEnumerable<regcovid_select_testdeviceResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_select_testdeviceResult"/> to an instance of <see cref="regcovid_select_testdeviceResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_select_testdeviceResultDto> ToDTOs(this IEnumerable<regcovid_select_testdeviceResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
