//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/> and <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/>.
    /// </summary>
    public static partial class regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/> converted from <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/>.</param>
        static partial void OnDTO(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1 entity, regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/> converted from <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/>.</param>
        static partial void OnEntity(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto dto, regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1 entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/> to convert.</param>
        public static regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1 ToEntity(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1();

            entity.NombreCompleto = dto.NombreCompleto;
            entity.ApePaterno = dto.ApePaterno;
            entity.ApeMaterno = dto.ApeMaterno;
            entity.Dni = dto.Dni;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/> to convert.</param>
        public static regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto ToDTO(this regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1 entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto();

            dto.NombreCompleto = entity.NombreCompleto;
            dto.ApePaterno = entity.ApePaterno;
            dto.ApeMaterno = entity.ApeMaterno;
            dto.Dni = entity.Dni;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1> ToEntities(this IEnumerable<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1"/> to an instance of <see cref="regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1Dto> ToDTOs(this IEnumerable<regcovid_positivosenviadosreg_vs_positivosrecividosvigResult1> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
