//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_servicios_vs_resultadosResult"/> and <see cref="regcovid_servicios_vs_resultadosResultDto"/>.
    /// </summary>
    public static partial class regcovid_servicios_vs_resultadosResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_servicios_vs_resultadosResultDto"/> converted from <see cref="regcovid_servicios_vs_resultadosResult"/>.</param>
        static partial void OnDTO(this regcovid_servicios_vs_resultadosResult entity, regcovid_servicios_vs_resultadosResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_servicios_vs_resultadosResult"/> converted from <see cref="regcovid_servicios_vs_resultadosResultDto"/>.</param>
        static partial void OnEntity(this regcovid_servicios_vs_resultadosResultDto dto, regcovid_servicios_vs_resultadosResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_servicios_vs_resultadosResultDto"/> to an instance of <see cref="regcovid_servicios_vs_resultadosResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_servicios_vs_resultadosResultDto"/> to convert.</param>
        public static regcovid_servicios_vs_resultadosResult ToEntity(this regcovid_servicios_vs_resultadosResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_servicios_vs_resultadosResult();

            entity.column0 = dto.column0;
            entity.v_DocNumber = dto.v_DocNumber;
            entity.Value1 = dto.Value1;
            entity.d_ServiceDate = dto.d_ServiceDate;
            entity.ValueSede = dto.ValueSede;
            entity.v_Sede = dto.v_Sede;
            entity.v_ServiceId = dto.v_ServiceId;
            entity.d_InsertDate = dto.d_InsertDate;
            entity.TecnicoCovid = dto.TecnicoCovid;
            entity.ComponentFieldId = dto.ComponentFieldId;
            entity.ServiceComponentFieldsId = dto.ServiceComponentFieldsId;
            entity.CorreoEnviado = dto.CorreoEnviado;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_servicios_vs_resultadosResult"/> to an instance of <see cref="regcovid_servicios_vs_resultadosResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_servicios_vs_resultadosResult"/> to convert.</param>
        public static regcovid_servicios_vs_resultadosResultDto ToDTO(this regcovid_servicios_vs_resultadosResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_servicios_vs_resultadosResultDto();

            dto.column0 = entity.column0;
            dto.v_DocNumber = entity.v_DocNumber;
            dto.Value1 = entity.Value1;
            dto.d_ServiceDate = entity.d_ServiceDate;
            dto.ValueSede = entity.ValueSede;
            dto.v_Sede = entity.v_Sede;
            dto.v_ServiceId = entity.v_ServiceId;
            dto.d_InsertDate = entity.d_InsertDate;
            dto.TecnicoCovid = entity.TecnicoCovid;
            dto.ComponentFieldId = entity.ComponentFieldId;
            dto.ServiceComponentFieldsId = entity.ServiceComponentFieldsId;
            dto.CorreoEnviado = entity.CorreoEnviado;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_servicios_vs_resultadosResultDto"/> to an instance of <see cref="regcovid_servicios_vs_resultadosResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_servicios_vs_resultadosResult> ToEntities(this IEnumerable<regcovid_servicios_vs_resultadosResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_servicios_vs_resultadosResult"/> to an instance of <see cref="regcovid_servicios_vs_resultadosResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_servicios_vs_resultadosResultDto> ToDTOs(this IEnumerable<regcovid_servicios_vs_resultadosResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
