//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:24
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_get_sedesResult"/> and <see cref="regcovid_get_sedesResultDto"/>.
    /// </summary>
    public static partial class regcovid_get_sedesResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_sedesResultDto"/> converted from <see cref="regcovid_get_sedesResult"/>.</param>
        static partial void OnDTO(this regcovid_get_sedesResult entity, regcovid_get_sedesResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_sedesResult"/> converted from <see cref="regcovid_get_sedesResultDto"/>.</param>
        static partial void OnEntity(this regcovid_get_sedesResultDto dto, regcovid_get_sedesResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_sedesResultDto"/> to an instance of <see cref="regcovid_get_sedesResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_get_sedesResultDto"/> to convert.</param>
        public static regcovid_get_sedesResult ToEntity(this regcovid_get_sedesResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_get_sedesResult();

            entity.Sede = dto.Sede;
            entity.SedeId = dto.SedeId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_get_sedesResult"/> to an instance of <see cref="regcovid_get_sedesResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_get_sedesResult"/> to convert.</param>
        public static regcovid_get_sedesResultDto ToDTO(this regcovid_get_sedesResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_get_sedesResultDto();

            dto.Sede = entity.Sede;
            dto.SedeId = entity.SedeId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_sedesResultDto"/> to an instance of <see cref="regcovid_get_sedesResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_get_sedesResult> ToEntities(this IEnumerable<regcovid_get_sedesResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_get_sedesResult"/> to an instance of <see cref="regcovid_get_sedesResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_get_sedesResultDto> ToDTOs(this IEnumerable<regcovid_get_sedesResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
