//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:25
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="regcovid_sp_getempresasprincipalesResult"/> and <see cref="regcovid_sp_getempresasprincipalesResultDto"/>.
    /// </summary>
    public static partial class regcovid_sp_getempresasprincipalesResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_sp_getempresasprincipalesResultDto"/> converted from <see cref="regcovid_sp_getempresasprincipalesResult"/>.</param>
        static partial void OnDTO(this regcovid_sp_getempresasprincipalesResult entity, regcovid_sp_getempresasprincipalesResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_sp_getempresasprincipalesResult"/> converted from <see cref="regcovid_sp_getempresasprincipalesResultDto"/>.</param>
        static partial void OnEntity(this regcovid_sp_getempresasprincipalesResultDto dto, regcovid_sp_getempresasprincipalesResult entity);

        /// <summary>
        /// Converts this instance of <see cref="regcovid_sp_getempresasprincipalesResultDto"/> to an instance of <see cref="regcovid_sp_getempresasprincipalesResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="regcovid_sp_getempresasprincipalesResultDto"/> to convert.</param>
        public static regcovid_sp_getempresasprincipalesResult ToEntity(this regcovid_sp_getempresasprincipalesResultDto dto)
        {
            if (dto == null) return null;

            var entity = new regcovid_sp_getempresasprincipalesResult();

            entity.id = dto.id;
            entity.nombre = dto.nombre;
            entity.nombreAbrev = dto.nombreAbrev;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="regcovid_sp_getempresasprincipalesResult"/> to an instance of <see cref="regcovid_sp_getempresasprincipalesResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="regcovid_sp_getempresasprincipalesResult"/> to convert.</param>
        public static regcovid_sp_getempresasprincipalesResultDto ToDTO(this regcovid_sp_getempresasprincipalesResult entity)
        {
            if (entity == null) return null;

            var dto = new regcovid_sp_getempresasprincipalesResultDto();

            dto.id = entity.id;
            dto.nombre = entity.nombre;
            dto.nombreAbrev = entity.nombreAbrev;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_sp_getempresasprincipalesResultDto"/> to an instance of <see cref="regcovid_sp_getempresasprincipalesResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<regcovid_sp_getempresasprincipalesResult> ToEntities(this IEnumerable<regcovid_sp_getempresasprincipalesResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="regcovid_sp_getempresasprincipalesResult"/> to an instance of <see cref="regcovid_sp_getempresasprincipalesResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<regcovid_sp_getempresasprincipalesResultDto> ToDTOs(this IEnumerable<regcovid_sp_getempresasprincipalesResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
