//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="salus_comprobarresultadoslaboratorioResult1"/> and <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/>.
    /// </summary>
    public static partial class salus_comprobarresultadoslaboratorioResult1Assembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="salus_comprobarresultadoslaboratorioResult1Dto"/> converted from <see cref="salus_comprobarresultadoslaboratorioResult1"/>.</param>
        static partial void OnDTO(this salus_comprobarresultadoslaboratorioResult1 entity, salus_comprobarresultadoslaboratorioResult1Dto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="salus_comprobarresultadoslaboratorioResult1"/> converted from <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/>.</param>
        static partial void OnEntity(this salus_comprobarresultadoslaboratorioResult1Dto dto, salus_comprobarresultadoslaboratorioResult1 entity);

        /// <summary>
        /// Converts this instance of <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult1"/>.
        /// </summary>
        /// <param name="dto"><see cref="salus_comprobarresultadoslaboratorioResult1Dto"/> to convert.</param>
        public static salus_comprobarresultadoslaboratorioResult1 ToEntity(this salus_comprobarresultadoslaboratorioResult1Dto dto)
        {
            if (dto == null) return null;

            var entity = new salus_comprobarresultadoslaboratorioResult1();

            entity.column0 = dto.column0;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="salus_comprobarresultadoslaboratorioResult1"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/>.
        /// </summary>
        /// <param name="entity"><see cref="salus_comprobarresultadoslaboratorioResult1"/> to convert.</param>
        public static salus_comprobarresultadoslaboratorioResult1Dto ToDTO(this salus_comprobarresultadoslaboratorioResult1 entity)
        {
            if (entity == null) return null;

            var dto = new salus_comprobarresultadoslaboratorioResult1Dto();

            dto.column0 = entity.column0;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult1"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<salus_comprobarresultadoslaboratorioResult1> ToEntities(this IEnumerable<salus_comprobarresultadoslaboratorioResult1Dto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="salus_comprobarresultadoslaboratorioResult1"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult1Dto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<salus_comprobarresultadoslaboratorioResult1Dto> ToDTOs(this IEnumerable<salus_comprobarresultadoslaboratorioResult1> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
