//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="salus_comprobarresultadoslaboratorioResult"/> and <see cref="salus_comprobarresultadoslaboratorioResultDto"/>.
    /// </summary>
    public static partial class salus_comprobarresultadoslaboratorioResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="salus_comprobarresultadoslaboratorioResultDto"/> converted from <see cref="salus_comprobarresultadoslaboratorioResult"/>.</param>
        static partial void OnDTO(this salus_comprobarresultadoslaboratorioResult entity, salus_comprobarresultadoslaboratorioResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="salus_comprobarresultadoslaboratorioResult"/> converted from <see cref="salus_comprobarresultadoslaboratorioResultDto"/>.</param>
        static partial void OnEntity(this salus_comprobarresultadoslaboratorioResultDto dto, salus_comprobarresultadoslaboratorioResult entity);

        /// <summary>
        /// Converts this instance of <see cref="salus_comprobarresultadoslaboratorioResultDto"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="salus_comprobarresultadoslaboratorioResultDto"/> to convert.</param>
        public static salus_comprobarresultadoslaboratorioResult ToEntity(this salus_comprobarresultadoslaboratorioResultDto dto)
        {
            if (dto == null) return null;

            var entity = new salus_comprobarresultadoslaboratorioResult();

            entity.v_ServiceId = dto.v_ServiceId;
            entity.TecnicoCovid = dto.TecnicoCovid;
            entity.ComponentFieldId = dto.ComponentFieldId;
            entity.ServiceComponentFieldsId = dto.ServiceComponentFieldsId;
            entity.Value1 = dto.Value1;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="salus_comprobarresultadoslaboratorioResult"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="salus_comprobarresultadoslaboratorioResult"/> to convert.</param>
        public static salus_comprobarresultadoslaboratorioResultDto ToDTO(this salus_comprobarresultadoslaboratorioResult entity)
        {
            if (entity == null) return null;

            var dto = new salus_comprobarresultadoslaboratorioResultDto();

            dto.v_ServiceId = entity.v_ServiceId;
            dto.TecnicoCovid = entity.TecnicoCovid;
            dto.ComponentFieldId = entity.ComponentFieldId;
            dto.ServiceComponentFieldsId = entity.ServiceComponentFieldsId;
            dto.Value1 = entity.Value1;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="salus_comprobarresultadoslaboratorioResultDto"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<salus_comprobarresultadoslaboratorioResult> ToEntities(this IEnumerable<salus_comprobarresultadoslaboratorioResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="salus_comprobarresultadoslaboratorioResult"/> to an instance of <see cref="salus_comprobarresultadoslaboratorioResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<salus_comprobarresultadoslaboratorioResultDto> ToDTOs(this IEnumerable<salus_comprobarresultadoslaboratorioResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
