//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:50
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="testdevice"/> and <see cref="testdeviceDto"/>.
    /// </summary>
    public static partial class testdeviceAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="testdeviceDto"/> converted from <see cref="testdevice"/>.</param>
        static partial void OnDTO(this testdevice entity, testdeviceDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="testdevice"/> converted from <see cref="testdeviceDto"/>.</param>
        static partial void OnEntity(this testdeviceDto dto, testdevice entity);

        /// <summary>
        /// Converts this instance of <see cref="testdeviceDto"/> to an instance of <see cref="testdevice"/>.
        /// </summary>
        /// <param name="dto"><see cref="testdeviceDto"/> to convert.</param>
        public static testdevice ToEntity(this testdeviceDto dto)
        {
            if (dto == null) return null;

            var entity = new testdevice();

            entity.iTestDeviceId = dto.iTestDeviceId;
            entity.vTestDeviceName = dto.vTestDeviceName;
            entity.vTestDeviceDescription = dto.vTestDeviceDescription;
            entity.iTestDeviceIdBrand = dto.iTestDeviceIdBrand;
            entity.vTestDeviceLot = dto.vTestDeviceLot;
            entity.dTestDeviceDueDate = dto.dTestDeviceDueDate;
            entity.iTestDeviceState = dto.iTestDeviceState;
            entity.iDeleted = dto.iDeleted;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="testdevice"/> to an instance of <see cref="testdeviceDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="testdevice"/> to convert.</param>
        public static testdeviceDto ToDTO(this testdevice entity)
        {
            if (entity == null) return null;

            var dto = new testdeviceDto();

            dto.iTestDeviceId = entity.iTestDeviceId;
            dto.vTestDeviceName = entity.vTestDeviceName;
            dto.vTestDeviceDescription = entity.vTestDeviceDescription;
            dto.iTestDeviceIdBrand = entity.iTestDeviceIdBrand;
            dto.vTestDeviceLot = entity.vTestDeviceLot;
            dto.dTestDeviceDueDate = entity.dTestDeviceDueDate;
            dto.iTestDeviceState = entity.iTestDeviceState;
            dto.iDeleted = entity.iDeleted;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="testdeviceDto"/> to an instance of <see cref="testdevice"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<testdevice> ToEntities(this IEnumerable<testdeviceDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="testdevice"/> to an instance of <see cref="testdeviceDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<testdeviceDto> ToDTOs(this IEnumerable<testdevice> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
