//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_authorization_regcovidResult"/> and <see cref="usp_authorization_regcovidResultDto"/>.
    /// </summary>
    public static partial class usp_authorization_regcovidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_authorization_regcovidResultDto"/> converted from <see cref="usp_authorization_regcovidResult"/>.</param>
        static partial void OnDTO(this usp_authorization_regcovidResult entity, usp_authorization_regcovidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_authorization_regcovidResult"/> converted from <see cref="usp_authorization_regcovidResultDto"/>.</param>
        static partial void OnEntity(this usp_authorization_regcovidResultDto dto, usp_authorization_regcovidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_authorization_regcovidResultDto"/> to an instance of <see cref="usp_authorization_regcovidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_authorization_regcovidResultDto"/> to convert.</param>
        public static usp_authorization_regcovidResult ToEntity(this usp_authorization_regcovidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_authorization_regcovidResult();

            entity.UsuarioRegcovidId = dto.UsuarioRegcovidId;
            entity.OrganizationId = dto.OrganizationId;
            entity.ProtocolId = dto.ProtocolId;
            entity.NodeId = dto.NodeId;
            entity.NodeName = dto.NodeName;
            entity.UserName = dto.UserName;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_authorization_regcovidResult"/> to an instance of <see cref="usp_authorization_regcovidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_authorization_regcovidResult"/> to convert.</param>
        public static usp_authorization_regcovidResultDto ToDTO(this usp_authorization_regcovidResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_authorization_regcovidResultDto();

            dto.UsuarioRegcovidId = entity.UsuarioRegcovidId;
            dto.OrganizationId = entity.OrganizationId;
            dto.ProtocolId = entity.ProtocolId;
            dto.NodeId = entity.NodeId;
            dto.NodeName = entity.NodeName;
            dto.UserName = entity.UserName;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_authorization_regcovidResultDto"/> to an instance of <see cref="usp_authorization_regcovidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_authorization_regcovidResult> ToEntities(this IEnumerable<usp_authorization_regcovidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_authorization_regcovidResult"/> to an instance of <see cref="usp_authorization_regcovidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_authorization_regcovidResultDto> ToDTOs(this IEnumerable<usp_authorization_regcovidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
