//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_getpersonbydocumentResult"/> and <see cref="usp_getpersonbydocumentResultDto"/>.
    /// </summary>
    public static partial class usp_getpersonbydocumentResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_getpersonbydocumentResultDto"/> converted from <see cref="usp_getpersonbydocumentResult"/>.</param>
        static partial void OnDTO(this usp_getpersonbydocumentResult entity, usp_getpersonbydocumentResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_getpersonbydocumentResult"/> converted from <see cref="usp_getpersonbydocumentResultDto"/>.</param>
        static partial void OnEntity(this usp_getpersonbydocumentResultDto dto, usp_getpersonbydocumentResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_getpersonbydocumentResultDto"/> to an instance of <see cref="usp_getpersonbydocumentResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_getpersonbydocumentResultDto"/> to convert.</param>
        public static usp_getpersonbydocumentResult ToEntity(this usp_getpersonbydocumentResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_getpersonbydocumentResult();

            entity.PersonId = dto.PersonId;
            entity.FirstName = dto.FirstName;
            entity.FirstLastName = dto.FirstLastName;
            entity.SecondLastName = dto.SecondLastName;
            entity.DocTypeId = dto.DocTypeId;
            entity.DocNumber = dto.DocNumber;
            entity.SexTypeId = dto.SexTypeId;
            entity.Birthdate = dto.Birthdate;
            entity.Mail = dto.Mail;
            entity.TelephoneNumber = dto.TelephoneNumber;
            entity.CurrentOccupation = dto.CurrentOccupation;
            entity.AdressLocation = dto.AdressLocation;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_getpersonbydocumentResult"/> to an instance of <see cref="usp_getpersonbydocumentResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_getpersonbydocumentResult"/> to convert.</param>
        public static usp_getpersonbydocumentResultDto ToDTO(this usp_getpersonbydocumentResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_getpersonbydocumentResultDto();

            dto.PersonId = entity.PersonId;
            dto.FirstName = entity.FirstName;
            dto.FirstLastName = entity.FirstLastName;
            dto.SecondLastName = entity.SecondLastName;
            dto.DocTypeId = entity.DocTypeId;
            dto.DocNumber = entity.DocNumber;
            dto.SexTypeId = entity.SexTypeId;
            dto.Birthdate = entity.Birthdate;
            dto.Mail = entity.Mail;
            dto.TelephoneNumber = entity.TelephoneNumber;
            dto.CurrentOccupation = entity.CurrentOccupation;
            dto.AdressLocation = entity.AdressLocation;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_getpersonbydocumentResultDto"/> to an instance of <see cref="usp_getpersonbydocumentResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_getpersonbydocumentResult> ToEntities(this IEnumerable<usp_getpersonbydocumentResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_getpersonbydocumentResult"/> to an instance of <see cref="usp_getpersonbydocumentResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_getpersonbydocumentResultDto> ToDTOs(this IEnumerable<usp_getpersonbydocumentResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
