//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_resultados_covid_get_resultadosResult"/> and <see cref="usp_resultados_covid_get_resultadosResultDto"/>.
    /// </summary>
    public static partial class usp_resultados_covid_get_resultadosResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_resultados_covid_get_resultadosResultDto"/> converted from <see cref="usp_resultados_covid_get_resultadosResult"/>.</param>
        static partial void OnDTO(this usp_resultados_covid_get_resultadosResult entity, usp_resultados_covid_get_resultadosResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_resultados_covid_get_resultadosResult"/> converted from <see cref="usp_resultados_covid_get_resultadosResultDto"/>.</param>
        static partial void OnEntity(this usp_resultados_covid_get_resultadosResultDto dto, usp_resultados_covid_get_resultadosResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_resultados_covid_get_resultadosResultDto"/> to an instance of <see cref="usp_resultados_covid_get_resultadosResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_resultados_covid_get_resultadosResultDto"/> to convert.</param>
        public static usp_resultados_covid_get_resultadosResult ToEntity(this usp_resultados_covid_get_resultadosResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_resultados_covid_get_resultadosResult();

            entity.Nro = dto.Nro;
            entity.Trabajador = dto.Trabajador;
            entity.Sede = dto.Sede;
            entity.Examen = dto.Examen;
            entity.Fecha = dto.Fecha;
            entity.Archivo = dto.Archivo;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_resultados_covid_get_resultadosResult"/> to an instance of <see cref="usp_resultados_covid_get_resultadosResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_resultados_covid_get_resultadosResult"/> to convert.</param>
        public static usp_resultados_covid_get_resultadosResultDto ToDTO(this usp_resultados_covid_get_resultadosResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_resultados_covid_get_resultadosResultDto();

            dto.Nro = entity.Nro;
            dto.Trabajador = entity.Trabajador;
            dto.Sede = entity.Sede;
            dto.Examen = entity.Examen;
            dto.Fecha = entity.Fecha;
            dto.Archivo = entity.Archivo;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_resultados_covid_get_resultadosResultDto"/> to an instance of <see cref="usp_resultados_covid_get_resultadosResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_resultados_covid_get_resultadosResult> ToEntities(this IEnumerable<usp_resultados_covid_get_resultadosResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_resultados_covid_get_resultadosResult"/> to an instance of <see cref="usp_resultados_covid_get_resultadosResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_resultados_covid_get_resultadosResultDto> ToDTOs(this IEnumerable<usp_resultados_covid_get_resultadosResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
