//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_resultados_covid_login_externosResult"/> and <see cref="usp_resultados_covid_login_externosResultDto"/>.
    /// </summary>
    public static partial class usp_resultados_covid_login_externosResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_resultados_covid_login_externosResultDto"/> converted from <see cref="usp_resultados_covid_login_externosResult"/>.</param>
        static partial void OnDTO(this usp_resultados_covid_login_externosResult entity, usp_resultados_covid_login_externosResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_resultados_covid_login_externosResult"/> converted from <see cref="usp_resultados_covid_login_externosResultDto"/>.</param>
        static partial void OnEntity(this usp_resultados_covid_login_externosResultDto dto, usp_resultados_covid_login_externosResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_resultados_covid_login_externosResultDto"/> to an instance of <see cref="usp_resultados_covid_login_externosResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_resultados_covid_login_externosResultDto"/> to convert.</param>
        public static usp_resultados_covid_login_externosResult ToEntity(this usp_resultados_covid_login_externosResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_resultados_covid_login_externosResult();

            entity.v_Usuario = dto.v_Usuario;
            entity.v_Nombres = dto.v_Nombres;
            entity.v_Apellidos = dto.v_Apellidos;
            entity.v_OrganizationId = dto.v_OrganizationId;
            entity.v_Name = dto.v_Name;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_resultados_covid_login_externosResult"/> to an instance of <see cref="usp_resultados_covid_login_externosResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_resultados_covid_login_externosResult"/> to convert.</param>
        public static usp_resultados_covid_login_externosResultDto ToDTO(this usp_resultados_covid_login_externosResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_resultados_covid_login_externosResultDto();

            dto.v_Usuario = entity.v_Usuario;
            dto.v_Nombres = entity.v_Nombres;
            dto.v_Apellidos = entity.v_Apellidos;
            dto.v_OrganizationId = entity.v_OrganizationId;
            dto.v_Name = entity.v_Name;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_resultados_covid_login_externosResultDto"/> to an instance of <see cref="usp_resultados_covid_login_externosResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_resultados_covid_login_externosResult> ToEntities(this IEnumerable<usp_resultados_covid_login_externosResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_resultados_covid_login_externosResult"/> to an instance of <see cref="usp_resultados_covid_login_externosResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_resultados_covid_login_externosResultDto> ToDTOs(this IEnumerable<usp_resultados_covid_login_externosResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
