//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:27
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_notificacion_vigcovidResult"/> and <see cref="usp_notificacion_vigcovidResultDto"/>.
    /// </summary>
    public static partial class usp_notificacion_vigcovidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_notificacion_vigcovidResultDto"/> converted from <see cref="usp_notificacion_vigcovidResult"/>.</param>
        static partial void OnDTO(this usp_notificacion_vigcovidResult entity, usp_notificacion_vigcovidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_notificacion_vigcovidResult"/> converted from <see cref="usp_notificacion_vigcovidResultDto"/>.</param>
        static partial void OnEntity(this usp_notificacion_vigcovidResultDto dto, usp_notificacion_vigcovidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_notificacion_vigcovidResultDto"/> to an instance of <see cref="usp_notificacion_vigcovidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_notificacion_vigcovidResultDto"/> to convert.</param>
        public static usp_notificacion_vigcovidResult ToEntity(this usp_notificacion_vigcovidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_notificacion_vigcovidResult();

            entity.Id = dto.Id;
            entity.Trabajador = dto.Trabajador;
            entity.FechaIngreso = dto.FechaIngreso;
            entity.Dni = dto.Dni;
            entity.Edad = dto.Edad;
            entity.Empleadora = dto.Empleadora;
            entity.PuestoTrabajo = dto.PuestoTrabajo;
            entity.EmailTrabajador = dto.EmailTrabajador;
            entity.EmailAnalista = dto.EmailAnalista;
            entity.EmailBP = dto.EmailBP;
            entity.EmailChampion = dto.EmailChampion;
            entity.EmailSeguridadFisica = dto.EmailSeguridadFisica;
            entity.MedicoVigila = dto.MedicoVigila;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_notificacion_vigcovidResult"/> to an instance of <see cref="usp_notificacion_vigcovidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_notificacion_vigcovidResult"/> to convert.</param>
        public static usp_notificacion_vigcovidResultDto ToDTO(this usp_notificacion_vigcovidResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_notificacion_vigcovidResultDto();

            dto.Id = entity.Id;
            dto.Trabajador = entity.Trabajador;
            dto.FechaIngreso = entity.FechaIngreso;
            dto.Dni = entity.Dni;
            dto.Edad = entity.Edad;
            dto.Empleadora = entity.Empleadora;
            dto.PuestoTrabajo = entity.PuestoTrabajo;
            dto.EmailTrabajador = entity.EmailTrabajador;
            dto.EmailAnalista = entity.EmailAnalista;
            dto.EmailBP = entity.EmailBP;
            dto.EmailChampion = entity.EmailChampion;
            dto.EmailSeguridadFisica = entity.EmailSeguridadFisica;
            dto.MedicoVigila = entity.MedicoVigila;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_notificacion_vigcovidResultDto"/> to an instance of <see cref="usp_notificacion_vigcovidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_notificacion_vigcovidResult> ToEntities(this IEnumerable<usp_notificacion_vigcovidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_notificacion_vigcovidResult"/> to an instance of <see cref="usp_notificacion_vigcovidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_notificacion_vigcovidResultDto> ToDTOs(this IEnumerable<usp_notificacion_vigcovidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
