//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_get_secuentialResult"/> and <see cref="usp_get_secuentialResultDto"/>.
    /// </summary>
    public static partial class usp_get_secuentialResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_secuentialResultDto"/> converted from <see cref="usp_get_secuentialResult"/>.</param>
        static partial void OnDTO(this usp_get_secuentialResult entity, usp_get_secuentialResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_secuentialResult"/> converted from <see cref="usp_get_secuentialResultDto"/>.</param>
        static partial void OnEntity(this usp_get_secuentialResultDto dto, usp_get_secuentialResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_get_secuentialResultDto"/> to an instance of <see cref="usp_get_secuentialResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_secuentialResultDto"/> to convert.</param>
        public static usp_get_secuentialResult ToEntity(this usp_get_secuentialResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_get_secuentialResult();

            entity.NewId = dto.NewId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_get_secuentialResult"/> to an instance of <see cref="usp_get_secuentialResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_secuentialResult"/> to convert.</param>
        public static usp_get_secuentialResultDto ToDTO(this usp_get_secuentialResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_get_secuentialResultDto();

            dto.NewId = entity.NewId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_secuentialResultDto"/> to an instance of <see cref="usp_get_secuentialResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_get_secuentialResult> ToEntities(this IEnumerable<usp_get_secuentialResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_secuentialResult"/> to an instance of <see cref="usp_get_secuentialResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_get_secuentialResultDto> ToDTOs(this IEnumerable<usp_get_secuentialResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
