//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/> and <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/>.
    /// </summary>
    public static partial class usp_get_servicecomponentfieldvaluesbyservicecomponentidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/> converted from <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/>.</param>
        static partial void OnDTO(this usp_get_servicecomponentfieldvaluesbyservicecomponentidResult entity, usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/> converted from <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/>.</param>
        static partial void OnEntity(this usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto dto, usp_get_servicecomponentfieldvaluesbyservicecomponentidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/> to an instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/> to convert.</param>
        public static usp_get_servicecomponentfieldvaluesbyservicecomponentidResult ToEntity(this usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_get_servicecomponentfieldvaluesbyservicecomponentidResult();

            entity.ServiceComponentFieldValuesId = dto.ServiceComponentFieldValuesId;
            entity.ComponentFieldId = dto.ComponentFieldId;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/> to an instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/> to convert.</param>
        public static usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto ToDTO(this usp_get_servicecomponentfieldvaluesbyservicecomponentidResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto();

            dto.ServiceComponentFieldValuesId = entity.ServiceComponentFieldValuesId;
            dto.ComponentFieldId = entity.ComponentFieldId;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/> to an instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_get_servicecomponentfieldvaluesbyservicecomponentidResult> ToEntities(this IEnumerable<usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResult"/> to an instance of <see cref="usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_get_servicecomponentfieldvaluesbyservicecomponentidResultDto> ToDTOs(this IEnumerable<usp_get_servicecomponentfieldvaluesbyservicecomponentidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
