//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:26
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usp_get_protocolcomponentbyprotocolidResult"/> and <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/>.
    /// </summary>
    public static partial class usp_get_protocolcomponentbyprotocolidResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_protocolcomponentbyprotocolidResultDto"/> converted from <see cref="usp_get_protocolcomponentbyprotocolidResult"/>.</param>
        static partial void OnDTO(this usp_get_protocolcomponentbyprotocolidResult entity, usp_get_protocolcomponentbyprotocolidResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_protocolcomponentbyprotocolidResult"/> converted from <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/>.</param>
        static partial void OnEntity(this usp_get_protocolcomponentbyprotocolidResultDto dto, usp_get_protocolcomponentbyprotocolidResult entity);

        /// <summary>
        /// Converts this instance of <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/> to an instance of <see cref="usp_get_protocolcomponentbyprotocolidResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="usp_get_protocolcomponentbyprotocolidResultDto"/> to convert.</param>
        public static usp_get_protocolcomponentbyprotocolidResult ToEntity(this usp_get_protocolcomponentbyprotocolidResultDto dto)
        {
            if (dto == null) return null;

            var entity = new usp_get_protocolcomponentbyprotocolidResult();

            entity.ComponentId = dto.ComponentId;
            entity.Price = dto.Price;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usp_get_protocolcomponentbyprotocolidResult"/> to an instance of <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usp_get_protocolcomponentbyprotocolidResult"/> to convert.</param>
        public static usp_get_protocolcomponentbyprotocolidResultDto ToDTO(this usp_get_protocolcomponentbyprotocolidResult entity)
        {
            if (entity == null) return null;

            var dto = new usp_get_protocolcomponentbyprotocolidResultDto();

            dto.ComponentId = entity.ComponentId;
            dto.Price = entity.Price;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/> to an instance of <see cref="usp_get_protocolcomponentbyprotocolidResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usp_get_protocolcomponentbyprotocolidResult> ToEntities(this IEnumerable<usp_get_protocolcomponentbyprotocolidResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usp_get_protocolcomponentbyprotocolidResult"/> to an instance of <see cref="usp_get_protocolcomponentbyprotocolidResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usp_get_protocolcomponentbyprotocolidResultDto> ToDTOs(this IEnumerable<usp_get_protocolcomponentbyprotocolidResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
