//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:28
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="uspgetemployeesResult"/> and <see cref="uspgetemployeesResultDto"/>.
    /// </summary>
    public static partial class uspgetemployeesResultAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="uspgetemployeesResultDto"/> converted from <see cref="uspgetemployeesResult"/>.</param>
        static partial void OnDTO(this uspgetemployeesResult entity, uspgetemployeesResultDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="uspgetemployeesResult"/> converted from <see cref="uspgetemployeesResultDto"/>.</param>
        static partial void OnEntity(this uspgetemployeesResultDto dto, uspgetemployeesResult entity);

        /// <summary>
        /// Converts this instance of <see cref="uspgetemployeesResultDto"/> to an instance of <see cref="uspgetemployeesResult"/>.
        /// </summary>
        /// <param name="dto"><see cref="uspgetemployeesResultDto"/> to convert.</param>
        public static uspgetemployeesResult ToEntity(this uspgetemployeesResultDto dto)
        {
            if (dto == null) return null;

            var entity = new uspgetemployeesResult();

            entity.Id = dto.Id;
            entity.IdentificationType = dto.IdentificationType;
            entity.NationalIDNumber = dto.NationalIDNumber;
            entity.Gender = dto.Gender;
            entity.FirstName = dto.FirstName;
            entity.MiddleName = dto.MiddleName;
            entity.LastName = dto.LastName;
            entity.BirthDate = dto.BirthDate;
            entity.EmailAddress = dto.EmailAddress;
            entity.Job = dto.Job;
            entity.AddressLine1 = dto.AddressLine1;
            entity.Hire = dto.Hire;
            entity.Headquarter = dto.Headquarter;
            entity.Employer = dto.Employer;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="uspgetemployeesResult"/> to an instance of <see cref="uspgetemployeesResultDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="uspgetemployeesResult"/> to convert.</param>
        public static uspgetemployeesResultDto ToDTO(this uspgetemployeesResult entity)
        {
            if (entity == null) return null;

            var dto = new uspgetemployeesResultDto();

            dto.Id = entity.Id;
            dto.IdentificationType = entity.IdentificationType;
            dto.NationalIDNumber = entity.NationalIDNumber;
            dto.Gender = entity.Gender;
            dto.FirstName = entity.FirstName;
            dto.MiddleName = entity.MiddleName;
            dto.LastName = entity.LastName;
            dto.BirthDate = entity.BirthDate;
            dto.EmailAddress = entity.EmailAddress;
            dto.Job = entity.Job;
            dto.AddressLine1 = entity.AddressLine1;
            dto.Hire = entity.Hire;
            dto.Headquarter = entity.Headquarter;
            dto.Employer = entity.Employer;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="uspgetemployeesResultDto"/> to an instance of <see cref="uspgetemployeesResult"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<uspgetemployeesResult> ToEntities(this IEnumerable<uspgetemployeesResultDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="uspgetemployeesResult"/> to an instance of <see cref="uspgetemployeesResultDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<uspgetemployeesResultDto> ToDTOs(this IEnumerable<uspgetemployeesResult> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
