//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2021/05/17 - 17:34:51
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using Sigesoft.Node.WinClient.DAL;

namespace Sigesoft.Node.WinClient.BE
{

    /// <summary>
    /// Assembler for <see cref="usuarioregcovidorganization"/> and <see cref="usuarioregcovidorganizationDto"/>.
    /// </summary>
    public static partial class usuarioregcovidorganizationAssembler
    {
        /// <summary>
        /// Invoked when <see cref="ToDTO"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="usuarioregcovidorganizationDto"/> converted from <see cref="usuarioregcovidorganization"/>.</param>
        static partial void OnDTO(this usuarioregcovidorganization entity, usuarioregcovidorganizationDto dto);

        /// <summary>
        /// Invoked when <see cref="ToEntity"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="usuarioregcovidorganization"/> converted from <see cref="usuarioregcovidorganizationDto"/>.</param>
        static partial void OnEntity(this usuarioregcovidorganizationDto dto, usuarioregcovidorganization entity);

        /// <summary>
        /// Converts this instance of <see cref="usuarioregcovidorganizationDto"/> to an instance of <see cref="usuarioregcovidorganization"/>.
        /// </summary>
        /// <param name="dto"><see cref="usuarioregcovidorganizationDto"/> to convert.</param>
        public static usuarioregcovidorganization ToEntity(this usuarioregcovidorganizationDto dto)
        {
            if (dto == null) return null;

            var entity = new usuarioregcovidorganization();

            entity.i_uro = dto.i_uro;
            entity.v_organizationId = dto.v_organizationId;
            entity.i_usuarioRegcovidId = dto.i_usuarioRegcovidId;
            entity.i_typeUser = dto.i_typeUser;
            entity.i_deleted = dto.i_deleted;
            entity.i_active = dto.i_active;
            entity.i_userCreate = dto.i_userCreate;
            entity.d_dateCreate = dto.d_dateCreate;
            entity.i_userUpdate = dto.i_userUpdate;
            entity.d_dateUpdate = dto.d_dateUpdate;
            entity.i_userDelete = dto.i_userDelete;
            entity.d_dateDelete = dto.d_dateDelete;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="usuarioregcovidorganization"/> to an instance of <see cref="usuarioregcovidorganizationDto"/>.
        /// </summary>
        /// <param name="entity"><see cref="usuarioregcovidorganization"/> to convert.</param>
        public static usuarioregcovidorganizationDto ToDTO(this usuarioregcovidorganization entity)
        {
            if (entity == null) return null;

            var dto = new usuarioregcovidorganizationDto();

            dto.i_uro = entity.i_uro;
            dto.v_organizationId = entity.v_organizationId;
            dto.i_usuarioRegcovidId = entity.i_usuarioRegcovidId;
            dto.i_typeUser = entity.i_typeUser;
            dto.i_deleted = entity.i_deleted;
            dto.i_active = entity.i_active;
            dto.i_userCreate = entity.i_userCreate;
            dto.d_dateCreate = entity.d_dateCreate;
            dto.i_userUpdate = entity.i_userUpdate;
            dto.d_dateUpdate = entity.d_dateUpdate;
            dto.i_userDelete = entity.i_userDelete;
            dto.d_dateDelete = entity.d_dateDelete;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="usuarioregcovidorganizationDto"/> to an instance of <see cref="usuarioregcovidorganization"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<usuarioregcovidorganization> ToEntities(this IEnumerable<usuarioregcovidorganizationDto> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToEntity()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="usuarioregcovidorganization"/> to an instance of <see cref="usuarioregcovidorganizationDto"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<usuarioregcovidorganizationDto> ToDTOs(this IEnumerable<usuarioregcovidorganization> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToDTO()).ToList();
        }

    }
}
